#-------------------------------------------------------------------------------
#- Copyright (c) 2019 Arista Networks, Inc. All rights reserved.
#-------------------------------------------------------------------------------
#- Maintainers:
#-   fdk-support@arista.com
#-
#- Description:
#-   Specific Board Standard Constraints
#-
#-   Licensed under BSD 3-clause license:
#-     https://opensource.org/licenses/BSD-3-Clause
#-
#- Tags:
#-   license-bsd-3-clause
#-
#-------------------------------------------------------------------------------


################################################################################
## Configuration Assertions
################################################################################


# The VCCO voltage is set to 1.8 V on bank 0
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

# Compress the bitstream
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DISABLE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 63.8 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]


################################################################################
## Timing Assertions
##
## Arranged in the following order:
## - Primary clocks
## - Virtual clocks
## - Generated clocks
## - Clock groups
## - Input and Output delay constraints
################################################################################


create_clock -period   8.000  -name ts_clk        [get_ports ts_clk_in]
create_clock -period 100.000  -name ts_diff_clk   [get_ports ts_diff_clk_p]

create_clock -period 6.400    -name refclk_user_0 [get_ports {refclk_user_p[0]}]
create_clock -period 6.400    -name refclk_user_1 [get_ports {refclk_user_p[1]}]

create_clock -period 6.400    -name gt_refclk_0   [get_ports {gt_refclk_p[0]}]
create_clock -period 6.400    -name gt_refclk_1   [get_ports {gt_refclk_p[1]}]
create_clock -period 6.400    -name gt_refclk_2   [get_ports {gt_refclk_p[2]}]
create_clock -period 6.400    -name gt_refclk_3   [get_ports {gt_refclk_p[3]}]
create_clock -period 6.400    -name gt_refclk_4   [get_ports {gt_refclk_p[4]}]
create_clock -period 6.400    -name gt_refclk_5   [get_ports {gt_refclk_p[5]}]
create_clock -period 6.400    -name gt_refclk_6   [get_ports {gt_refclk_p[6]}]
create_clock -period 6.400    -name gt_refclk_7   [get_ports {gt_refclk_p[7]}]
create_clock -period 6.400    -name gt_refclk_8   [get_ports {gt_refclk_p[8]}]
create_clock -period 6.400    -name gt_refclk_9   [get_ports {gt_refclk_p[9]}]
create_clock -period 6.400    -name gt_refclk_10  [get_ports {gt_refclk_p[10]}]
create_clock -period 6.400    -name gt_refclk_11  [get_ports {gt_refclk_p[11]}]
create_clock -period 6.400    -name gt_refclk_12  [get_ports {gt_refclk_p[12]}]
create_clock -period 6.400    -name gt_refclk_13  [get_ports {gt_refclk_p[13]}]
create_clock -period 6.400    -name gt_refclk_14  [get_ports {gt_refclk_p[14]}]
create_clock -period 8.000    -name gt_refclk_15  [get_ports {gt_refclk_p[15]}]
create_clock -period 8.000    -name gt_refclk_16  [get_ports {gt_refclk_p[16]}]
create_clock -period 8.000    -name gt_refclk_17  [get_ports {gt_refclk_p[17]}]
create_clock -period 8.000    -name gt_refclk_18  [get_ports {gt_refclk_p[18]}]
create_clock -period 8.000    -name gt_refclk_19  [get_ports {gt_refclk_p[19]}]
create_clock -period 8.000    -name gt_refclk_20  [get_ports {gt_refclk_p[20]}]
create_clock -period 8.000    -name gt_refclk_21  [get_ports {gt_refclk_p[21]}]
create_clock -period 6.400    -name gt_refclk_22  [get_ports {gt_refclk_p[22]}]
create_clock -period 6.400    -name gt_refclk_23  [get_ports {gt_refclk_p[23]}]

create_clock -period 10.000   -name pcie_refclk   [get_ports pcie_refclk_p]

create_clock -period 2500.000 -name i2c_clk_0     [get_ports {i2c_scl[0]}]
create_clock -period 2500.000 -name i2c_clk_1     [get_ports {i2c_scl[1]}]
create_clock -period 2500.000 -name i2c_clk_2     [get_ports {i2c_scl[2]}]
create_clock -period 2500.000 -name i2c_clk_3     [get_ports {i2c_scl[3]}]
create_clock -period 2500.000 -name i2c_clk_4     [get_ports {i2c_scl[4]}]
create_clock -period 2500.000 -name i2c_clk_5     [get_ports {i2c_scl[5]}]
create_clock -period 2500.000 -name i2c_clk_6     [get_ports {i2c_scl[6]}]

create_generated_clock -name sem_clk -source [get_pins bufg_sem_clock/I] -divide_by 2 [get_pins bufg_sem_clock/O]
create_generated_clock -name refclk_25 [get_pins -hier -filter {NAME =~ arista_sysctl_i*/refclk_pll_i/*CLKOUT0}]
create_generated_clock -name refclk_50 [get_pins -hier -filter {NAME =~ arista_sysctl_i*/refclk_pll_i/*CLKOUT1}]


################################################################################
## Timing Exceptions
##
## Arranged in the following order:
## - Primary clocks
## - False paths
## - Max delay/min delay
## - Multicycle paths
## - Case analysis
## - Disable Timing
################################################################################


set_false_path -from [get_ports pcie_perst_n]


################################################################################
## Physical Constraints
## (Can be in a separate file to the above timing constraints)
################################################################################


set_property PACKAGE_PIN BB9 [get_ports ts_clk_in]
set_property PACKAGE_PIN AY26 [get_ports ts_diff_clk_p]
set_property PACKAGE_PIN AY27 [get_ports ts_diff_clk_n]
set_property PACKAGE_PIN BC8 [get_ports ts_clk_out]
set_property PACKAGE_PIN BC7 [get_ports ts_clk_clksel_n]
set_property IOSTANDARD LVCMOS18 [get_ports ts_clk_in]
set_property IOSTANDARD LVCMOS18 [get_ports ts_clk_out]
set_property IOSTANDARD LVCMOS18 [get_ports ts_clk_clksel_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports ts_diff_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports ts_diff_clk_n]

set_property PACKAGE_PIN BA9 [get_ports pps_in_n]
set_property PACKAGE_PIN BA7 [get_ports pps_out]
set_property IOSTANDARD LVCMOS18 [get_ports pps_in_n]
set_property IOSTANDARD LVCMOS18 [get_ports pps_out]

set_property PACKAGE_PIN BA13 [get_ports {refclk_user_n[0]}]
set_property PACKAGE_PIN AY13 [get_ports {refclk_user_p[0]}]
set_property PACKAGE_PIN AY28 [get_ports {refclk_user_n[1]}]
set_property PACKAGE_PIN AW28 [get_ports {refclk_user_p[1]}]
set_property IOSTANDARD LVDS [get_ports {refclk_user_p[0]}]
set_property IOSTANDARD LVDS [get_ports {refclk_user_n[0]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {refclk_user_p[1]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {refclk_user_n[1]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {refclk_user_p[0]}]

set_property PACKAGE_PIN BB10 [get_ports refclk_out_n]
set_property PACKAGE_PIN BB11 [get_ports refclk_out_p]
set_property IOSTANDARD LVDS [get_ports refclk_out_p]
set_property IOSTANDARD LVDS [get_ports refclk_out_n]

set_property PACKAGE_PIN BB26 [get_ports sync_in_p]
set_property PACKAGE_PIN BB27 [get_ports sync_in_n]
set_property PACKAGE_PIN AP13 [get_ports sync_out_p]
set_property PACKAGE_PIN AR13 [get_ports sync_out_n]
set_property IOSTANDARD LVDS [get_ports sync_in_p]
set_property IOSTANDARD LVDS [get_ports sync_in_n]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports sync_out_p]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports sync_out_n]
set_property DIFF_TERM_ADV TERM_NONE [get_ports sync_in_p]

set_property PACKAGE_PIN AH11 [get_ports {gt_refclk_p[0]}]
set_property PACKAGE_PIN AH10 [get_ports {gt_refclk_n[0]}]
set_property PACKAGE_PIN AD11 [get_ports {gt_refclk_p[1]}]
set_property PACKAGE_PIN AD10 [get_ports {gt_refclk_n[1]}]
set_property PACKAGE_PIN Y11  [get_ports {gt_refclk_p[2]}]
set_property PACKAGE_PIN Y10  [get_ports {gt_refclk_n[2]}]
set_property PACKAGE_PIN T11  [get_ports {gt_refclk_p[3]}]
set_property PACKAGE_PIN T10  [get_ports {gt_refclk_n[3]}]
set_property PACKAGE_PIN M11  [get_ports {gt_refclk_p[4]}]
set_property PACKAGE_PIN M10  [get_ports {gt_refclk_n[4]}]
set_property PACKAGE_PIN H11  [get_ports {gt_refclk_p[5]}]
set_property PACKAGE_PIN H10  [get_ports {gt_refclk_n[5]}]
set_property PACKAGE_PIN D11  [get_ports {gt_refclk_p[6]}]
set_property PACKAGE_PIN D10  [get_ports {gt_refclk_n[6]}]
set_property PACKAGE_PIN AV38 [get_ports {gt_refclk_p[7]}]
set_property PACKAGE_PIN AV39 [get_ports {gt_refclk_n[7]}]
set_property PACKAGE_PIN AR36 [get_ports {gt_refclk_p[8]}]
set_property PACKAGE_PIN AR37 [get_ports {gt_refclk_n[8]}]
set_property PACKAGE_PIN AL36 [get_ports {gt_refclk_p[9]}]
set_property PACKAGE_PIN AL37 [get_ports {gt_refclk_n[9]}]
set_property PACKAGE_PIN AG36 [get_ports {gt_refclk_p[10]}]
set_property PACKAGE_PIN AG37 [get_ports {gt_refclk_n[10]}]
set_property PACKAGE_PIN AC36 [get_ports {gt_refclk_p[11]}]
set_property PACKAGE_PIN AC37 [get_ports {gt_refclk_n[11]}]
set_property PACKAGE_PIN W36  [get_ports {gt_refclk_p[12]}]
set_property PACKAGE_PIN W37  [get_ports {gt_refclk_n[12]}]
set_property PACKAGE_PIN R36  [get_ports {gt_refclk_p[13]}]
set_property PACKAGE_PIN R37  [get_ports {gt_refclk_n[13]}]
set_property PACKAGE_PIN L36  [get_ports {gt_refclk_p[14]}]
set_property PACKAGE_PIN L37  [get_ports {gt_refclk_n[14]}]
set_property PACKAGE_PIN AF11 [get_ports {gt_refclk_p[15]}]
set_property PACKAGE_PIN AF10 [get_ports {gt_refclk_n[15]}]
set_property PACKAGE_PIN V11  [get_ports {gt_refclk_p[16]}]
set_property PACKAGE_PIN V10  [get_ports {gt_refclk_n[16]}]
set_property PACKAGE_PIN K11  [get_ports {gt_refclk_p[17]}]
set_property PACKAGE_PIN K10  [get_ports {gt_refclk_n[17]}]
set_property PACKAGE_PIN B11  [get_ports {gt_refclk_p[18]}]
set_property PACKAGE_PIN B10  [get_ports {gt_refclk_n[18]}]
set_property PACKAGE_PIN AN36 [get_ports {gt_refclk_p[19]}]
set_property PACKAGE_PIN AN37 [get_ports {gt_refclk_n[19]}]
set_property PACKAGE_PIN U36  [get_ports {gt_refclk_p[20]}]
set_property PACKAGE_PIN U37  [get_ports {gt_refclk_n[20]}]
set_property PACKAGE_PIN K38  [get_ports {gt_refclk_p[21]}]
set_property PACKAGE_PIN K39  [get_ports {gt_refclk_n[21]}]
set_property PACKAGE_PIN AM11 [get_ports {gt_refclk_p[22]}]
set_property PACKAGE_PIN AM10 [get_ports {gt_refclk_n[22]}]
set_property PACKAGE_PIN BA40 [get_ports {gt_refclk_p[23]}]
set_property PACKAGE_PIN BA41 [get_ports {gt_refclk_n[23]}]

set_property PACKAGE_PIN AJ4  [get_ports {gt_rx_p[1]}]
set_property PACKAGE_PIN AJ3  [get_ports {gt_rx_n[1]}]
set_property PACKAGE_PIN AJ9  [get_ports {gt_tx_p[1]}]
set_property PACKAGE_PIN AJ8  [get_ports {gt_tx_n[1]}]
set_property PACKAGE_PIN AH2  [get_ports {gt_rx_p[2]}]
set_property PACKAGE_PIN AH1  [get_ports {gt_rx_n[2]}]
set_property PACKAGE_PIN AH7  [get_ports {gt_tx_p[2]}]
set_property PACKAGE_PIN AH6  [get_ports {gt_tx_n[2]}]
set_property PACKAGE_PIN AG4  [get_ports {gt_rx_p[3]}]
set_property PACKAGE_PIN AG3  [get_ports {gt_rx_n[3]}]
set_property PACKAGE_PIN AG9  [get_ports {gt_tx_p[3]}]
set_property PACKAGE_PIN AG8  [get_ports {gt_tx_n[3]}]
set_property PACKAGE_PIN AF2  [get_ports {gt_rx_p[4]}]
set_property PACKAGE_PIN AF1  [get_ports {gt_rx_n[4]}]
set_property PACKAGE_PIN AF7  [get_ports {gt_tx_p[4]}]
set_property PACKAGE_PIN AF6  [get_ports {gt_tx_n[4]}]
set_property PACKAGE_PIN AE3  [get_ports {gt_rx_n[5]}]
set_property PACKAGE_PIN AE4  [get_ports {gt_rx_p[5]}]
set_property PACKAGE_PIN AE8  [get_ports {gt_tx_n[5]}]
set_property PACKAGE_PIN AE9  [get_ports {gt_tx_p[5]}]
set_property PACKAGE_PIN AD1  [get_ports {gt_rx_n[6]}]
set_property PACKAGE_PIN AD2  [get_ports {gt_rx_p[6]}]
set_property PACKAGE_PIN AD6  [get_ports {gt_tx_n[6]}]
set_property PACKAGE_PIN AD7  [get_ports {gt_tx_p[6]}]
set_property PACKAGE_PIN AC3  [get_ports {gt_rx_n[7]}]
set_property PACKAGE_PIN AC4  [get_ports {gt_rx_p[7]}]
set_property PACKAGE_PIN AC8  [get_ports {gt_tx_n[7]}]
set_property PACKAGE_PIN AC9  [get_ports {gt_tx_p[7]}]
set_property PACKAGE_PIN AB1  [get_ports {gt_rx_n[8]}]
set_property PACKAGE_PIN AB2  [get_ports {gt_rx_p[8]}]
set_property PACKAGE_PIN AB6  [get_ports {gt_tx_n[8]}]
set_property PACKAGE_PIN AB7  [get_ports {gt_tx_p[8]}]
set_property PACKAGE_PIN AA3  [get_ports {gt_rx_n[9]}]
set_property PACKAGE_PIN AA4  [get_ports {gt_rx_p[9]}]
set_property PACKAGE_PIN AA8  [get_ports {gt_tx_n[9]}]
set_property PACKAGE_PIN AA9  [get_ports {gt_tx_p[9]}]
set_property PACKAGE_PIN Y1   [get_ports {gt_rx_n[10]}]
set_property PACKAGE_PIN Y2   [get_ports {gt_rx_p[10]}]
set_property PACKAGE_PIN Y6   [get_ports {gt_tx_n[10]}]
set_property PACKAGE_PIN Y7   [get_ports {gt_tx_p[10]}]
set_property PACKAGE_PIN W3   [get_ports {gt_rx_n[11]}]
set_property PACKAGE_PIN W4   [get_ports {gt_rx_p[11]}]
set_property PACKAGE_PIN W8   [get_ports {gt_tx_n[11]}]
set_property PACKAGE_PIN W9   [get_ports {gt_tx_p[11]}]
set_property PACKAGE_PIN V1   [get_ports {gt_rx_n[12]}]
set_property PACKAGE_PIN V2   [get_ports {gt_rx_p[12]}]
set_property PACKAGE_PIN V6   [get_ports {gt_tx_n[12]}]
set_property PACKAGE_PIN V7   [get_ports {gt_tx_p[12]}]
set_property PACKAGE_PIN U3   [get_ports {gt_rx_n[13]}]
set_property PACKAGE_PIN U4   [get_ports {gt_rx_p[13]}]
set_property PACKAGE_PIN U8   [get_ports {gt_tx_n[13]}]
set_property PACKAGE_PIN U9   [get_ports {gt_tx_p[13]}]
set_property PACKAGE_PIN T1   [get_ports {gt_rx_n[14]}]
set_property PACKAGE_PIN T2   [get_ports {gt_rx_p[14]}]
set_property PACKAGE_PIN T6   [get_ports {gt_tx_n[14]}]
set_property PACKAGE_PIN T7   [get_ports {gt_tx_p[14]}]
set_property PACKAGE_PIN R3   [get_ports {gt_rx_n[15]}]
set_property PACKAGE_PIN R4   [get_ports {gt_rx_p[15]}]
set_property PACKAGE_PIN R9   [get_ports {gt_tx_p[15]}]
set_property PACKAGE_PIN R8   [get_ports {gt_tx_n[15]}]
set_property PACKAGE_PIN P1   [get_ports {gt_rx_n[16]}]
set_property PACKAGE_PIN P2   [get_ports {gt_rx_p[16]}]
set_property PACKAGE_PIN P6   [get_ports {gt_tx_n[16]}]
set_property PACKAGE_PIN P7   [get_ports {gt_tx_p[16]}]
set_property PACKAGE_PIN N3   [get_ports {gt_rx_n[17]}]
set_property PACKAGE_PIN N4   [get_ports {gt_rx_p[17]}]
set_property PACKAGE_PIN N8   [get_ports {gt_tx_n[17]}]
set_property PACKAGE_PIN N9   [get_ports {gt_tx_p[17]}]
set_property PACKAGE_PIN M1   [get_ports {gt_rx_n[18]}]
set_property PACKAGE_PIN M2   [get_ports {gt_rx_p[18]}]
set_property PACKAGE_PIN M6   [get_ports {gt_tx_n[18]}]
set_property PACKAGE_PIN M7   [get_ports {gt_tx_p[18]}]
set_property PACKAGE_PIN L3   [get_ports {gt_rx_n[19]}]
set_property PACKAGE_PIN L4   [get_ports {gt_rx_p[19]}]
set_property PACKAGE_PIN L8   [get_ports {gt_tx_n[19]}]
set_property PACKAGE_PIN L9   [get_ports {gt_tx_p[19]}]
set_property PACKAGE_PIN K1   [get_ports {gt_rx_n[20]}]
set_property PACKAGE_PIN K2   [get_ports {gt_rx_p[20]}]
set_property PACKAGE_PIN K7   [get_ports {gt_tx_p[20]}]
set_property PACKAGE_PIN K6   [get_ports {gt_tx_n[20]}]
set_property PACKAGE_PIN J4   [get_ports {gt_rx_p[21]}]
set_property PACKAGE_PIN J3   [get_ports {gt_rx_n[21]}]
set_property PACKAGE_PIN J9   [get_ports {gt_tx_p[21]}]
set_property PACKAGE_PIN J8   [get_ports {gt_tx_n[21]}]
set_property PACKAGE_PIN H2   [get_ports {gt_rx_p[22]}]
set_property PACKAGE_PIN H1   [get_ports {gt_rx_n[22]}]
set_property PACKAGE_PIN H7   [get_ports {gt_tx_p[22]}]
set_property PACKAGE_PIN H6   [get_ports {gt_tx_n[22]}]
set_property PACKAGE_PIN G4   [get_ports {gt_rx_p[23]}]
set_property PACKAGE_PIN G3   [get_ports {gt_rx_n[23]}]
set_property PACKAGE_PIN G9   [get_ports {gt_tx_p[23]}]
set_property PACKAGE_PIN G8   [get_ports {gt_tx_n[23]}]
set_property PACKAGE_PIN F2   [get_ports {gt_rx_p[24]}]
set_property PACKAGE_PIN F1   [get_ports {gt_rx_n[24]}]
set_property PACKAGE_PIN F7   [get_ports {gt_tx_p[24]}]
set_property PACKAGE_PIN F6   [get_ports {gt_tx_n[24]}]
set_property PACKAGE_PIN E4   [get_ports {gt_rx_p[25]}]
set_property PACKAGE_PIN E3   [get_ports {gt_rx_n[25]}]
set_property PACKAGE_PIN E9   [get_ports {gt_tx_p[25]}]
set_property PACKAGE_PIN E8   [get_ports {gt_tx_n[25]}]
set_property PACKAGE_PIN D2   [get_ports {gt_rx_p[26]}]
set_property PACKAGE_PIN D1   [get_ports {gt_rx_n[26]}]
set_property PACKAGE_PIN D7   [get_ports {gt_tx_p[26]}]
set_property PACKAGE_PIN D6   [get_ports {gt_tx_n[26]}]
set_property PACKAGE_PIN C4   [get_ports {gt_rx_p[27]}]
set_property PACKAGE_PIN C3   [get_ports {gt_rx_n[27]}]
set_property PACKAGE_PIN C9   [get_ports {gt_tx_p[27]}]
set_property PACKAGE_PIN C8   [get_ports {gt_tx_n[27]}]
set_property PACKAGE_PIN A5   [get_ports {gt_rx_p[28]}]
set_property PACKAGE_PIN A4   [get_ports {gt_rx_n[28]}]
set_property PACKAGE_PIN A9   [get_ports {gt_tx_p[28]}]
set_property PACKAGE_PIN A8   [get_ports {gt_tx_n[28]}]
set_property PACKAGE_PIN AU45 [get_ports {gt_rx_p[29]}]
set_property PACKAGE_PIN AU46 [get_ports {gt_rx_n[29]}]
set_property PACKAGE_PIN AU40 [get_ports {gt_tx_p[29]}]
set_property PACKAGE_PIN AU41 [get_ports {gt_tx_n[29]}]
set_property PACKAGE_PIN AT43 [get_ports {gt_rx_p[30]}]
set_property PACKAGE_PIN AT44 [get_ports {gt_rx_n[30]}]
set_property PACKAGE_PIN AT38 [get_ports {gt_tx_p[30]}]
set_property PACKAGE_PIN AT39 [get_ports {gt_tx_n[30]}]
set_property PACKAGE_PIN AR45 [get_ports {gt_rx_p[31]}]
set_property PACKAGE_PIN AR46 [get_ports {gt_rx_n[31]}]
set_property PACKAGE_PIN AR40 [get_ports {gt_tx_p[31]}]
set_property PACKAGE_PIN AR41 [get_ports {gt_tx_n[31]}]
set_property PACKAGE_PIN AP43 [get_ports {gt_rx_p[32]}]
set_property PACKAGE_PIN AP44 [get_ports {gt_rx_n[32]}]
set_property PACKAGE_PIN AP38 [get_ports {gt_tx_p[32]}]
set_property PACKAGE_PIN AP39 [get_ports {gt_tx_n[32]}]
set_property PACKAGE_PIN AN45 [get_ports {gt_rx_p[33]}]
set_property PACKAGE_PIN AN46 [get_ports {gt_rx_n[33]}]
set_property PACKAGE_PIN AN40 [get_ports {gt_tx_p[33]}]
set_property PACKAGE_PIN AN41 [get_ports {gt_tx_n[33]}]
set_property PACKAGE_PIN AM43 [get_ports {gt_rx_p[34]}]
set_property PACKAGE_PIN AM44 [get_ports {gt_rx_n[34]}]
set_property PACKAGE_PIN AM38 [get_ports {gt_tx_p[34]}]
set_property PACKAGE_PIN AM39 [get_ports {gt_tx_n[34]}]
set_property PACKAGE_PIN AL45 [get_ports {gt_rx_p[35]}]
set_property PACKAGE_PIN AL46 [get_ports {gt_rx_n[35]}]
set_property PACKAGE_PIN AL40 [get_ports {gt_tx_p[35]}]
set_property PACKAGE_PIN AL41 [get_ports {gt_tx_n[35]}]
set_property PACKAGE_PIN AK43 [get_ports {gt_rx_p[36]}]
set_property PACKAGE_PIN AK44 [get_ports {gt_rx_n[36]}]
set_property PACKAGE_PIN AK38 [get_ports {gt_tx_p[36]}]
set_property PACKAGE_PIN AK39 [get_ports {gt_tx_n[36]}]
set_property PACKAGE_PIN AJ45 [get_ports {gt_rx_p[37]}]
set_property PACKAGE_PIN AJ46 [get_ports {gt_rx_n[37]}]
set_property PACKAGE_PIN AJ40 [get_ports {gt_tx_p[37]}]
set_property PACKAGE_PIN AJ41 [get_ports {gt_tx_n[37]}]
set_property PACKAGE_PIN AH43 [get_ports {gt_rx_p[38]}]
set_property PACKAGE_PIN AH44 [get_ports {gt_rx_n[38]}]
set_property PACKAGE_PIN AH38 [get_ports {gt_tx_p[38]}]
set_property PACKAGE_PIN AH39 [get_ports {gt_tx_n[38]}]
set_property PACKAGE_PIN AG45 [get_ports {gt_rx_p[39]}]
set_property PACKAGE_PIN AG46 [get_ports {gt_rx_n[39]}]
set_property PACKAGE_PIN AG40 [get_ports {gt_tx_p[39]}]
set_property PACKAGE_PIN AG41 [get_ports {gt_tx_n[39]}]
set_property PACKAGE_PIN AF43 [get_ports {gt_rx_p[40]}]
set_property PACKAGE_PIN AF44 [get_ports {gt_rx_n[40]}]
set_property PACKAGE_PIN AF38 [get_ports {gt_tx_p[40]}]
set_property PACKAGE_PIN AF39 [get_ports {gt_tx_n[40]}]
set_property PACKAGE_PIN AE45 [get_ports {gt_rx_p[41]}]
set_property PACKAGE_PIN AE46 [get_ports {gt_rx_n[41]}]
set_property PACKAGE_PIN AE40 [get_ports {gt_tx_p[41]}]
set_property PACKAGE_PIN AE41 [get_ports {gt_tx_n[41]}]
set_property PACKAGE_PIN AD43 [get_ports {gt_rx_p[42]}]
set_property PACKAGE_PIN AD44 [get_ports {gt_rx_n[42]}]
set_property PACKAGE_PIN AD38 [get_ports {gt_tx_p[42]}]
set_property PACKAGE_PIN AD39 [get_ports {gt_tx_n[42]}]
set_property PACKAGE_PIN AC45 [get_ports {gt_rx_p[43]}]
set_property PACKAGE_PIN AC46 [get_ports {gt_rx_n[43]}]
set_property PACKAGE_PIN AC40 [get_ports {gt_tx_p[43]}]
set_property PACKAGE_PIN AC41 [get_ports {gt_tx_n[43]}]
set_property PACKAGE_PIN AB43 [get_ports {gt_rx_p[44]}]
set_property PACKAGE_PIN AB44 [get_ports {gt_rx_n[44]}]
set_property PACKAGE_PIN AB38 [get_ports {gt_tx_p[44]}]
set_property PACKAGE_PIN AB39 [get_ports {gt_tx_n[44]}]
set_property PACKAGE_PIN AA45 [get_ports {gt_rx_p[45]}]
set_property PACKAGE_PIN AA46 [get_ports {gt_rx_n[45]}]
set_property PACKAGE_PIN AA40 [get_ports {gt_tx_p[45]}]
set_property PACKAGE_PIN AA41 [get_ports {gt_tx_n[45]}]
set_property PACKAGE_PIN Y43  [get_ports {gt_rx_p[46]}]
set_property PACKAGE_PIN Y44  [get_ports {gt_rx_n[46]}]
set_property PACKAGE_PIN Y38  [get_ports {gt_tx_p[46]}]
set_property PACKAGE_PIN Y39  [get_ports {gt_tx_n[46]}]
set_property PACKAGE_PIN W45  [get_ports {gt_rx_p[47]}]
set_property PACKAGE_PIN W46  [get_ports {gt_rx_n[47]}]
set_property PACKAGE_PIN W40  [get_ports {gt_tx_p[47]}]
set_property PACKAGE_PIN W41  [get_ports {gt_tx_n[47]}]
set_property PACKAGE_PIN V43  [get_ports {gt_rx_p[48]}]
set_property PACKAGE_PIN V44  [get_ports {gt_rx_n[48]}]
set_property PACKAGE_PIN V38  [get_ports {gt_tx_p[48]}]
set_property PACKAGE_PIN V39  [get_ports {gt_tx_n[48]}]
set_property PACKAGE_PIN U45  [get_ports {gt_rx_p[49]}]
set_property PACKAGE_PIN U46  [get_ports {gt_rx_n[49]}]
set_property PACKAGE_PIN U40  [get_ports {gt_tx_p[49]}]
set_property PACKAGE_PIN U41  [get_ports {gt_tx_n[49]}]
set_property PACKAGE_PIN T43  [get_ports {gt_rx_p[50]}]
set_property PACKAGE_PIN T44  [get_ports {gt_rx_n[50]}]
set_property PACKAGE_PIN T38  [get_ports {gt_tx_p[50]}]
set_property PACKAGE_PIN T39  [get_ports {gt_tx_n[50]}]
set_property PACKAGE_PIN R45  [get_ports {gt_rx_p[51]}]
set_property PACKAGE_PIN R46  [get_ports {gt_rx_n[51]}]
set_property PACKAGE_PIN R40  [get_ports {gt_tx_p[51]}]
set_property PACKAGE_PIN R41  [get_ports {gt_tx_n[51]}]
set_property PACKAGE_PIN P43  [get_ports {gt_rx_p[52]}]
set_property PACKAGE_PIN P44  [get_ports {gt_rx_n[52]}]
set_property PACKAGE_PIN P38  [get_ports {gt_tx_p[52]}]
set_property PACKAGE_PIN P39  [get_ports {gt_tx_n[52]}]
set_property PACKAGE_PIN N45  [get_ports {gt_rx_p[53]}]
set_property PACKAGE_PIN N46  [get_ports {gt_rx_n[53]}]
set_property PACKAGE_PIN N40  [get_ports {gt_tx_p[53]}]
set_property PACKAGE_PIN N41  [get_ports {gt_tx_n[53]}]
set_property PACKAGE_PIN M43  [get_ports {gt_rx_p[54]}]
set_property PACKAGE_PIN M44  [get_ports {gt_rx_n[54]}]
set_property PACKAGE_PIN M38  [get_ports {gt_tx_p[54]}]
set_property PACKAGE_PIN M39  [get_ports {gt_tx_n[54]}]
set_property PACKAGE_PIN L45  [get_ports {gt_rx_p[55]}]
set_property PACKAGE_PIN L46  [get_ports {gt_rx_n[55]}]
set_property PACKAGE_PIN L40  [get_ports {gt_tx_p[55]}]
set_property PACKAGE_PIN L41  [get_ports {gt_tx_n[55]}]
set_property PACKAGE_PIN K43  [get_ports {gt_rx_p[56]}]
set_property PACKAGE_PIN K44  [get_ports {gt_rx_n[56]}]
set_property PACKAGE_PIN J40  [get_ports {gt_tx_p[56]}]
set_property PACKAGE_PIN J41  [get_ports {gt_tx_n[56]}]
set_property PACKAGE_PIN J45  [get_ports {gt_rx_p[57]}]
set_property PACKAGE_PIN J46  [get_ports {gt_rx_n[57]}]
set_property PACKAGE_PIN G40  [get_ports {gt_tx_p[57]}]
set_property PACKAGE_PIN G41  [get_ports {gt_tx_n[57]}]
set_property PACKAGE_PIN H43  [get_ports {gt_rx_p[58]}]
set_property PACKAGE_PIN H44  [get_ports {gt_rx_n[58]}]
set_property PACKAGE_PIN E42  [get_ports {gt_tx_p[58]}]
set_property PACKAGE_PIN E43  [get_ports {gt_tx_n[58]}]
set_property PACKAGE_PIN F45  [get_ports {gt_rx_p[59]}]
set_property PACKAGE_PIN F46  [get_ports {gt_rx_n[59]}]
set_property PACKAGE_PIN C42  [get_ports {gt_tx_p[59]}]
set_property PACKAGE_PIN C43  [get_ports {gt_tx_n[59]}]
set_property PACKAGE_PIN D45  [get_ports {gt_rx_p[60]}]
set_property PACKAGE_PIN D46  [get_ports {gt_rx_n[60]}]
set_property PACKAGE_PIN A42  [get_ports {gt_tx_p[60]}]
set_property PACKAGE_PIN A43  [get_ports {gt_tx_n[60]}]
set_property PACKAGE_PIN AN4  [get_ports {gt_rx_p[61]}]
set_property PACKAGE_PIN AN3  [get_ports {gt_rx_n[61]}]
set_property PACKAGE_PIN AN9  [get_ports {gt_tx_p[61]}]
set_property PACKAGE_PIN AN8  [get_ports {gt_tx_n[61]}]
set_property PACKAGE_PIN AM2  [get_ports {gt_rx_p[62]}]
set_property PACKAGE_PIN AM1  [get_ports {gt_rx_n[62]}]
set_property PACKAGE_PIN AM7  [get_ports {gt_tx_p[62]}]
set_property PACKAGE_PIN AM6  [get_ports {gt_tx_n[62]}]
set_property PACKAGE_PIN AL4  [get_ports {gt_rx_p[63]}]
set_property PACKAGE_PIN AL3  [get_ports {gt_rx_n[63]}]
set_property PACKAGE_PIN AL9  [get_ports {gt_tx_p[63]}]
set_property PACKAGE_PIN AL8  [get_ports {gt_tx_n[63]}]
set_property PACKAGE_PIN AK2  [get_ports {gt_rx_p[64]}]
set_property PACKAGE_PIN AK1  [get_ports {gt_rx_n[64]}]
set_property PACKAGE_PIN AK7  [get_ports {gt_tx_p[64]}]
set_property PACKAGE_PIN AK6  [get_ports {gt_tx_n[64]}]
set_property PACKAGE_PIN BC45 [get_ports {gt_rx_p[65]}]
set_property PACKAGE_PIN BC46 [get_ports {gt_rx_n[65]}]
set_property PACKAGE_PIN BF42 [get_ports {gt_tx_p[65]}]
set_property PACKAGE_PIN BF43 [get_ports {gt_tx_n[65]}]
set_property PACKAGE_PIN BA45 [get_ports {gt_rx_p[66]}]
set_property PACKAGE_PIN BA46 [get_ports {gt_rx_n[66]}]
set_property PACKAGE_PIN BD42 [get_ports {gt_tx_p[66]}]
set_property PACKAGE_PIN BD43 [get_ports {gt_tx_n[66]}]
set_property PACKAGE_PIN AW45 [get_ports {gt_rx_p[67]}]
set_property PACKAGE_PIN AW46 [get_ports {gt_rx_n[67]}]
set_property PACKAGE_PIN BB42 [get_ports {gt_tx_p[67]}]
set_property PACKAGE_PIN BB43 [get_ports {gt_tx_n[67]}]
set_property PACKAGE_PIN AV43 [get_ports {gt_rx_p[68]}]
set_property PACKAGE_PIN AV44 [get_ports {gt_rx_n[68]}]
set_property PACKAGE_PIN AW40 [get_ports {gt_tx_p[68]}]
set_property PACKAGE_PIN AW41 [get_ports {gt_tx_n[68]}]

set_property PACKAGE_PIN BC2  [get_ports {pcie_rx_p[7]}]
set_property PACKAGE_PIN BC1  [get_ports {pcie_rx_n[7]}]
set_property PACKAGE_PIN BF5  [get_ports {pcie_tx_p[7]}]
set_property PACKAGE_PIN BF4  [get_ports {pcie_tx_n[7]}]
set_property PACKAGE_PIN BA2  [get_ports {pcie_rx_p[6]}]
set_property PACKAGE_PIN BA1  [get_ports {pcie_rx_n[6]}]
set_property PACKAGE_PIN BD5  [get_ports {pcie_tx_p[6]}]
set_property PACKAGE_PIN BD4  [get_ports {pcie_tx_n[6]}]
set_property PACKAGE_PIN AW4  [get_ports {pcie_rx_p[5]}]
set_property PACKAGE_PIN AW3  [get_ports {pcie_rx_n[5]}]
set_property PACKAGE_PIN BB5  [get_ports {pcie_tx_p[5]}]
set_property PACKAGE_PIN BB4  [get_ports {pcie_tx_n[5]}]
set_property PACKAGE_PIN AV2  [get_ports {pcie_rx_p[4]}]
set_property PACKAGE_PIN AV1  [get_ports {pcie_rx_n[4]}]
set_property PACKAGE_PIN AV7  [get_ports {pcie_tx_p[4]}]
set_property PACKAGE_PIN AV6  [get_ports {pcie_tx_n[4]}]
set_property PACKAGE_PIN AU4  [get_ports {pcie_rx_p[3]}]
set_property PACKAGE_PIN AU3  [get_ports {pcie_rx_n[3]}]
set_property PACKAGE_PIN AU9  [get_ports {pcie_tx_p[3]}]
set_property PACKAGE_PIN AU8  [get_ports {pcie_tx_n[3]}]
set_property PACKAGE_PIN AT2  [get_ports {pcie_rx_p[2]}]
set_property PACKAGE_PIN AT1  [get_ports {pcie_rx_n[2]}]
set_property PACKAGE_PIN AT7  [get_ports {pcie_tx_p[2]}]
set_property PACKAGE_PIN AT6  [get_ports {pcie_tx_n[2]}]
set_property PACKAGE_PIN AR4  [get_ports {pcie_rx_p[1]}]
set_property PACKAGE_PIN AR3  [get_ports {pcie_rx_n[1]}]
set_property PACKAGE_PIN AR9  [get_ports {pcie_tx_p[1]}]
set_property PACKAGE_PIN AR8  [get_ports {pcie_tx_n[1]}]
set_property PACKAGE_PIN AP2  [get_ports {pcie_rx_p[0]}]
set_property PACKAGE_PIN AP1  [get_ports {pcie_rx_n[0]}]
set_property PACKAGE_PIN AP7  [get_ports {pcie_tx_p[0]}]
set_property PACKAGE_PIN AP6  [get_ports {pcie_tx_n[0]}]
set_property PACKAGE_PIN AT11 [get_ports pcie_refclk_p]
set_property PACKAGE_PIN AT10 [get_ports pcie_refclk_n]
set_property PACKAGE_PIN AR26 [get_ports pcie_perst_n]
set_property PACKAGE_PIN BF8  [get_ports pcie_wake_n]
set_property IOSTANDARD LVCMOS12 [get_ports pcie_perst_n]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_wake_n]
# Onboard Pullup for pcie_perst_n...
# Onboard Pulldown for pcie_wake_n...

set_property PACKAGE_PIN AM27 [get_ports {i2c_scl[0]}]
set_property PACKAGE_PIN AN27 [get_ports {i2c_sda[0]}]
set_property PACKAGE_PIN BF12 [get_ports {i2c_scl[1]}]
set_property PACKAGE_PIN BE12 [get_ports {i2c_sda[1]}]
set_property PACKAGE_PIN AP25 [get_ports {i2c_scl[2]}]
set_property PACKAGE_PIN AP26 [get_ports {i2c_sda[2]}]
set_property PACKAGE_PIN AN28 [get_ports {i2c_scl[3]}]
set_property PACKAGE_PIN AP28 [get_ports {i2c_sda[3]}]
set_property PACKAGE_PIN AL25 [get_ports {i2c_scl[4]}]
set_property PACKAGE_PIN AM25 [get_ports {i2c_sda[4]}]
set_property PACKAGE_PIN AM26 [get_ports {i2c_scl[5]}]
set_property PACKAGE_PIN AN26 [get_ports {i2c_sda[5]}]
set_property PACKAGE_PIN AL15 [get_ports {i2c_scl[6]}]
set_property PACKAGE_PIN AM15 [get_ports {i2c_sda[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_scl[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_sda[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i2c_scl[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i2c_sda[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_scl[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_sda[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_scl[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_sda[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_scl[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_sda[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_scl[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_sda[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_scl[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {i2c_sda[6]}]
set_property DRIVE 4 [get_ports {i2c_scl[*]}]
set_property DRIVE 8 [get_ports {i2c_sda[0]}]
set_property DRIVE 4 [get_ports {i2c_sda[1]}]
set_property DRIVE 4 [get_ports {i2c_sda[2]}]
set_property DRIVE 4 [get_ports {i2c_sda[3]}]
set_property DRIVE 4 [get_ports {i2c_sda[4]}]
set_property DRIVE 4 [get_ports {i2c_sda[5]}]
set_property DRIVE 4 [get_ports {i2c_sda[6]}]
set_property SLEW SLOW [get_ports {i2c_scl[*]}]
set_property SLEW SLOW [get_ports {i2c_sda[*]}]
# Onboard Pullups for the I2C Interfaces...
# Pullup I2C 6 since there are no onboard pullups for l/lb
set_property PULLUP TRUE [get_ports {i2c_scl[6]}]
set_property PULLUP TRUE [get_ports {i2c_sda[6]}]

set_property PACKAGE_PIN BD9  [get_ports dac_cs_n]
set_property PACKAGE_PIN BC12 [get_ports dac_spi_mosi]
set_property PACKAGE_PIN BC11 [get_ports dac_spi_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports dac_cs_n]
set_property IOSTANDARD LVCMOS18 [get_ports dac_spi_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports dac_spi_sclk]

set_property PACKAGE_PIN AH18 [get_ports vn]
set_property PACKAGE_PIN AG19 [get_ports vp]
set_property IOSTANDARD ANALOG [get_ports vp]
set_property IOSTANDARD ANALOG [get_ports vn]

set_property PACKAGE_PIN BF9  [get_ports {gpio[0]}]
set_property PACKAGE_PIN BF10 [get_ports {gpio[1]}]
set_property PACKAGE_PIN BF7  [get_ports {gpio[2]}]
set_property PACKAGE_PIN BE7  [get_ports {gpio[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio[*]}]
set_property DRIVE 4 [get_ports  {gpio[*]}]
set_property SLEW SLOW [get_ports  {gpio[*]}]

set_property PACKAGE_PIN AM14 [get_ports crc_error]
set_property IOSTANDARD LVCMOS12 [get_ports crc_error]
set_property DRIVE 4 [get_ports crc_error]
set_property SLEW SLOW [get_ports crc_error]

set_property PACKAGE_PIN BA8 [get_ports {fpga_id[0]}]
set_property PACKAGE_PIN BC9 [get_ports {fpga_id[1]}]
set_property PACKAGE_PIN BB7 [get_ports {fpga_id[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fpga_id[*]}]
set_property PULLUP TRUE [get_ports {fpga_id[*]}]

set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm0_sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm0_sys_clk_p]
set_property IOSTANDARD LVCMOS12        [get_ports dimm0_ddr4_reset_n]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm0_ddr4_dq[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm0_ddr4_dqs_c[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm0_ddr4_dqs_t[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm0_ddr4_ck_c[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm0_ddr4_ck_t[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm0_ddr4_adr[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm0_ddr4_ba[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm0_ddr4_bg[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm0_ddr4_cke[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm0_ddr4_odt[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm0_ddr4_cs_n[*]}]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm0_ddr4_dm_dbi_n[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm0_ddr4_act_n]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm0_ddr4_parity]
set_property SLEW FAST [get_ports {dimm0_ddr4_dq[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_dqs_c[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_dqs_t[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_ck_c[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_ck_t[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_adr[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_ba[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_bg[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_cke[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_odt[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_cs_n[*]}]
set_property SLEW FAST [get_ports {dimm0_ddr4_dm_dbi_n[*]}]
set_property SLEW FAST [get_ports dimm0_ddr4_act_n]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm0_ddr4_dq[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm0_ddr4_dqs_c[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm0_ddr4_dqs_t[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm0_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_dq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_dqs_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_dqs_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_ck_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_ck_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_adr[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_ba[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_bg[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_cke[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_odt[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_cs_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm0_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports dimm0_ddr4_act_n]

set_property PACKAGE_PIN K30 [get_ports dimm0_ddr4_act_n]
set_property PACKAGE_PIN T32 [get_ports {dimm0_ddr4_adr[0]}]
set_property PACKAGE_PIN P34 [get_ports {dimm0_ddr4_adr[1]}]
set_property PACKAGE_PIN N34 [get_ports {dimm0_ddr4_adr[2]}]
set_property PACKAGE_PIN M30 [get_ports {dimm0_ddr4_adr[3]}]
set_property PACKAGE_PIN M31 [get_ports {dimm0_ddr4_adr[4]}]
set_property PACKAGE_PIN L30 [get_ports {dimm0_ddr4_adr[5]}]
set_property PACKAGE_PIN M34 [get_ports {dimm0_ddr4_adr[6]}]
set_property PACKAGE_PIN L34 [get_ports {dimm0_ddr4_adr[7]}]
set_property PACKAGE_PIN M32 [get_ports {dimm0_ddr4_adr[8]}]
set_property PACKAGE_PIN L33 [get_ports {dimm0_ddr4_adr[9]}]
set_property PACKAGE_PIN V33 [get_ports {dimm0_ddr4_adr[10]}]
set_property PACKAGE_PIN K33 [get_ports {dimm0_ddr4_adr[11]}]
set_property PACKAGE_PIN L32 [get_ports {dimm0_ddr4_adr[12]}]
set_property PACKAGE_PIN U30 [get_ports {dimm0_ddr4_adr[13]}]
set_property PACKAGE_PIN U31 [get_ports {dimm0_ddr4_adr[14]}]
set_property PACKAGE_PIN R30 [get_ports {dimm0_ddr4_adr[15]}]
set_property PACKAGE_PIN U32 [get_ports {dimm0_ddr4_adr[16]}]
set_property PACKAGE_PIN P30 [get_ports {dimm0_ddr4_adr[17]}]
set_property PACKAGE_PIN P31 [get_ports {dimm0_ddr4_ba[0]}]
set_property PACKAGE_PIN U34 [get_ports {dimm0_ddr4_ba[1]}]
set_property PACKAGE_PIN K32 [get_ports {dimm0_ddr4_bg[0]}]
set_property PACKAGE_PIN K31 [get_ports {dimm0_ddr4_bg[1]}]
set_property PACKAGE_PIN R32 [get_ports {dimm0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN R33 [get_ports {dimm0_ddr4_ck_c[1]}]
set_property PACKAGE_PIN J30 [get_ports {dimm0_ddr4_cke[0]}]
set_property PACKAGE_PIN J31 [get_ports {dimm0_ddr4_cke[1]}]
set_property PACKAGE_PIN R31 [get_ports {dimm0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN T33 [get_ports {dimm0_ddr4_ck_t[1]}]
set_property PACKAGE_PIN V32 [get_ports {dimm0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN V31 [get_ports {dimm0_ddr4_cs_n[1]}]
set_property PACKAGE_PIN H37 [get_ports {dimm0_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN J26 [get_ports {dimm0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN C27 [get_ports {dimm0_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN B34 [get_ports {dimm0_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN E40 [get_ports {dimm0_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN G30 [get_ports {dimm0_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN T28 [get_ports {dimm0_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN M29 [get_ports {dimm0_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN C36 [get_ports {dimm0_ddr4_dm_dbi_n[8]}]
set_property PACKAGE_PIN H34 [get_ports {dimm0_ddr4_dq[0]}]
set_property PACKAGE_PIN F35 [get_ports {dimm0_ddr4_dq[1]}]
set_property PACKAGE_PIN F37 [get_ports {dimm0_ddr4_dq[2]}]
set_property PACKAGE_PIN J35 [get_ports {dimm0_ddr4_dq[3]}]
set_property PACKAGE_PIN F34 [get_ports {dimm0_ddr4_dq[4]}]
set_property PACKAGE_PIN G34 [get_ports {dimm0_ddr4_dq[5]}]
set_property PACKAGE_PIN G37 [get_ports {dimm0_ddr4_dq[6]}]
set_property PACKAGE_PIN J36 [get_ports {dimm0_ddr4_dq[7]}]
set_property PACKAGE_PIN H29 [get_ports {dimm0_ddr4_dq[8]}]
set_property PACKAGE_PIN G26 [get_ports {dimm0_ddr4_dq[9]}]
set_property PACKAGE_PIN E28 [get_ports {dimm0_ddr4_dq[10]}]
set_property PACKAGE_PIN D28 [get_ports {dimm0_ddr4_dq[11]}]
set_property PACKAGE_PIN G29 [get_ports {dimm0_ddr4_dq[12]}]
set_property PACKAGE_PIN G27 [get_ports {dimm0_ddr4_dq[13]}]
set_property PACKAGE_PIN F27 [get_ports {dimm0_ddr4_dq[14]}]
set_property PACKAGE_PIN E27 [get_ports {dimm0_ddr4_dq[15]}]
set_property PACKAGE_PIN C29 [get_ports {dimm0_ddr4_dq[16]}]
set_property PACKAGE_PIN B29 [get_ports {dimm0_ddr4_dq[17]}]
set_property PACKAGE_PIN A30 [get_ports {dimm0_ddr4_dq[18]}]
set_property PACKAGE_PIN E30 [get_ports {dimm0_ddr4_dq[19]}]
set_property PACKAGE_PIN B30 [get_ports {dimm0_ddr4_dq[20]}]
set_property PACKAGE_PIN D29 [get_ports {dimm0_ddr4_dq[21]}]
set_property PACKAGE_PIN A29 [get_ports {dimm0_ddr4_dq[22]}]
set_property PACKAGE_PIN D30 [get_ports {dimm0_ddr4_dq[23]}]
set_property PACKAGE_PIN D31 [get_ports {dimm0_ddr4_dq[24]}]
set_property PACKAGE_PIN D33 [get_ports {dimm0_ddr4_dq[25]}]
set_property PACKAGE_PIN C33 [get_ports {dimm0_ddr4_dq[26]}]
set_property PACKAGE_PIN D34 [get_ports {dimm0_ddr4_dq[27]}]
set_property PACKAGE_PIN C31 [get_ports {dimm0_ddr4_dq[28]}]
set_property PACKAGE_PIN C32 [get_ports {dimm0_ddr4_dq[29]}]
set_property PACKAGE_PIN B32 [get_ports {dimm0_ddr4_dq[30]}]
set_property PACKAGE_PIN C34 [get_ports {dimm0_ddr4_dq[31]}]
set_property PACKAGE_PIN A40 [get_ports {dimm0_ddr4_dq[32]}]
set_property PACKAGE_PIN C39 [get_ports {dimm0_ddr4_dq[33]}]
set_property PACKAGE_PIN E39 [get_ports {dimm0_ddr4_dq[34]}]
set_property PACKAGE_PIN E38 [get_ports {dimm0_ddr4_dq[35]}]
set_property PACKAGE_PIN C38 [get_ports {dimm0_ddr4_dq[36]}]
set_property PACKAGE_PIN B40 [get_ports {dimm0_ddr4_dq[37]}]
set_property PACKAGE_PIN D38 [get_ports {dimm0_ddr4_dq[38]}]
set_property PACKAGE_PIN D39 [get_ports {dimm0_ddr4_dq[39]}]
set_property PACKAGE_PIN F33 [get_ports {dimm0_ddr4_dq[40]}]
set_property PACKAGE_PIN F32 [get_ports {dimm0_ddr4_dq[41]}]
set_property PACKAGE_PIN G31 [get_ports {dimm0_ddr4_dq[42]}]
set_property PACKAGE_PIN H31 [get_ports {dimm0_ddr4_dq[43]}]
set_property PACKAGE_PIN E33 [get_ports {dimm0_ddr4_dq[44]}]
set_property PACKAGE_PIN E32 [get_ports {dimm0_ddr4_dq[45]}]
set_property PACKAGE_PIN G32 [get_ports {dimm0_ddr4_dq[46]}]
set_property PACKAGE_PIN H32 [get_ports {dimm0_ddr4_dq[47]}]
set_property PACKAGE_PIN N26 [get_ports {dimm0_ddr4_dq[48]}]
set_property PACKAGE_PIN P26 [get_ports {dimm0_ddr4_dq[49]}]
set_property PACKAGE_PIN R26 [get_ports {dimm0_ddr4_dq[50]}]
set_property PACKAGE_PIN T26 [get_ports {dimm0_ddr4_dq[51]}]
set_property PACKAGE_PIN N28 [get_ports {dimm0_ddr4_dq[52]}]
set_property PACKAGE_PIN P28 [get_ports {dimm0_ddr4_dq[53]}]
set_property PACKAGE_PIN R27 [get_ports {dimm0_ddr4_dq[54]}]
set_property PACKAGE_PIN T27 [get_ports {dimm0_ddr4_dq[55]}]
set_property PACKAGE_PIN L27 [get_ports {dimm0_ddr4_dq[56]}]
set_property PACKAGE_PIN K28 [get_ports {dimm0_ddr4_dq[57]}]
set_property PACKAGE_PIN H28 [get_ports {dimm0_ddr4_dq[58]}]
set_property PACKAGE_PIN H27 [get_ports {dimm0_ddr4_dq[59]}]
set_property PACKAGE_PIN M27 [get_ports {dimm0_ddr4_dq[60]}]
set_property PACKAGE_PIN L28 [get_ports {dimm0_ddr4_dq[61]}]
set_property PACKAGE_PIN J29 [get_ports {dimm0_ddr4_dq[62]}]
set_property PACKAGE_PIN J28 [get_ports {dimm0_ddr4_dq[63]}]
set_property PACKAGE_PIN B35 [get_ports {dimm0_ddr4_dq[64]}]
set_property PACKAGE_PIN A37 [get_ports {dimm0_ddr4_dq[65]}]
set_property PACKAGE_PIN D36 [get_ports {dimm0_ddr4_dq[66]}]
set_property PACKAGE_PIN E36 [get_ports {dimm0_ddr4_dq[67]}]
set_property PACKAGE_PIN A35 [get_ports {dimm0_ddr4_dq[68]}]
set_property PACKAGE_PIN D35 [get_ports {dimm0_ddr4_dq[69]}]
set_property PACKAGE_PIN E35 [get_ports {dimm0_ddr4_dq[70]}]
set_property PACKAGE_PIN A38 [get_ports {dimm0_ddr4_dq[71]}]
set_property PACKAGE_PIN G36 [get_ports {dimm0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN F29 [get_ports {dimm0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN A28 [get_ports {dimm0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN A33 [get_ports {dimm0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN A39 [get_ports {dimm0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN H33 [get_ports {dimm0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN N29 [get_ports {dimm0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN K27 [get_ports {dimm0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN B37 [get_ports {dimm0_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN H36 [get_ports {dimm0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN F28 [get_ports {dimm0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN A27 [get_ports {dimm0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN A32 [get_ports {dimm0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN B39 [get_ports {dimm0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN J33 [get_ports {dimm0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN P29 [get_ports {dimm0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN K26 [get_ports {dimm0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN B36 [get_ports {dimm0_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN T30 [get_ports {dimm0_ddr4_odt[0]}]
set_property PACKAGE_PIN N31 [get_ports {dimm0_ddr4_odt[1]}]
set_property PACKAGE_PIN T34 [get_ports dimm0_ddr4_parity]
set_property PACKAGE_PIN E31 [get_ports dimm0_ddr4_reset_n]
set_property PACKAGE_PIN N33 [get_ports dimm0_sys_clk_n]
set_property PACKAGE_PIN N32 [get_ports dimm0_sys_clk_p]

set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm1_sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm1_sys_clk_p]
set_property IOSTANDARD LVCMOS12        [get_ports dimm1_ddr4_reset_n]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm1_ddr4_dq[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm1_ddr4_dqs_c[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm1_ddr4_dqs_t[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm1_ddr4_ck_c[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm1_ddr4_ck_t[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm1_ddr4_adr[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm1_ddr4_ba[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm1_ddr4_bg[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm1_ddr4_cke[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm1_ddr4_odt[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm1_ddr4_cs_n[*]}]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm1_ddr4_dm_dbi_n[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm1_ddr4_act_n]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm1_ddr4_parity]
set_property SLEW FAST [get_ports {dimm1_ddr4_dq[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_dqs_c[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_dqs_t[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_ck_c[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_ck_t[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_adr[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_ba[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_bg[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_cke[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_odt[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_cs_n[*]}]
set_property SLEW FAST [get_ports {dimm1_ddr4_dm_dbi_n[*]}]
set_property SLEW FAST [get_ports dimm1_ddr4_act_n]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm1_ddr4_dq[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm1_ddr4_dqs_c[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm1_ddr4_dqs_t[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm1_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_dq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_dqs_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_dqs_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_ck_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_ck_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_adr[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_ba[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_bg[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_cke[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_odt[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_cs_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm1_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports dimm1_ddr4_act_n]

set_property PACKAGE_PIN AL34 [get_ports dimm1_ddr4_act_n]
set_property PACKAGE_PIN BA34 [get_ports {dimm1_ddr4_adr[0]}]
set_property PACKAGE_PIN AW34 [get_ports {dimm1_ddr4_adr[1]}]
set_property PACKAGE_PIN AW33 [get_ports {dimm1_ddr4_adr[2]}]
set_property PACKAGE_PIN AV34 [get_ports {dimm1_ddr4_adr[3]}]
set_property PACKAGE_PIN AT33 [get_ports {dimm1_ddr4_adr[4]}]
set_property PACKAGE_PIN AV33 [get_ports {dimm1_ddr4_adr[5]}]
set_property PACKAGE_PIN AT34 [get_ports {dimm1_ddr4_adr[6]}]
set_property PACKAGE_PIN AP33 [get_ports {dimm1_ddr4_adr[7]}]
set_property PACKAGE_PIN AR33 [get_ports {dimm1_ddr4_adr[8]}]
set_property PACKAGE_PIN AP34 [get_ports {dimm1_ddr4_adr[9]}]
set_property PACKAGE_PIN BB37 [get_ports {dimm1_ddr4_adr[10]}]
set_property PACKAGE_PIN AN33 [get_ports {dimm1_ddr4_adr[11]}]
set_property PACKAGE_PIN AN34 [get_ports {dimm1_ddr4_adr[12]}]
set_property PACKAGE_PIN BD35 [get_ports {dimm1_ddr4_adr[13]}]
set_property PACKAGE_PIN BB36 [get_ports {dimm1_ddr4_adr[14]}]
set_property PACKAGE_PIN BC34 [get_ports {dimm1_ddr4_adr[15]}]
set_property PACKAGE_PIN BC37 [get_ports {dimm1_ddr4_adr[16]}]
set_property PACKAGE_PIN BE35 [get_ports {dimm1_ddr4_adr[17]}]
set_property PACKAGE_PIN BB34 [get_ports {dimm1_ddr4_ba[0]}]
set_property PACKAGE_PIN AY35 [get_ports {dimm1_ddr4_ba[1]}]
set_property PACKAGE_PIN AM34 [get_ports {dimm1_ddr4_bg[0]}]
set_property PACKAGE_PIN AN32 [get_ports {dimm1_ddr4_bg[1]}]
set_property PACKAGE_PIN AW36 [get_ports {dimm1_ddr4_ck_c[0]}]
set_property PACKAGE_PIN BA33 [get_ports {dimm1_ddr4_ck_c[1]}]
set_property PACKAGE_PIN AL32 [get_ports {dimm1_ddr4_cke[0]}]
set_property PACKAGE_PIN AM32 [get_ports {dimm1_ddr4_cke[1]}]
set_property PACKAGE_PIN AW35 [get_ports {dimm1_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AY33 [get_ports {dimm1_ddr4_ck_t[1]}]
set_property PACKAGE_PIN BC36 [get_ports {dimm1_ddr4_cs_n[0]}]
set_property PACKAGE_PIN BE36 [get_ports {dimm1_ddr4_cs_n[1]}]
set_property PACKAGE_PIN AE31 [get_ports {dimm1_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN AA32 [get_ports {dimm1_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN AJ27 [get_ports {dimm1_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN AP31 [get_ports {dimm1_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN BF39 [get_ports {dimm1_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN BF32 [get_ports {dimm1_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN AW29 [get_ports {dimm1_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN AH34 [get_ports {dimm1_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN BC31 [get_ports {dimm1_ddr4_dm_dbi_n[8]}]
set_property PACKAGE_PIN AE33 [get_ports {dimm1_ddr4_dq[0]}]
set_property PACKAGE_PIN AD33 [get_ports {dimm1_ddr4_dq[1]}]
set_property PACKAGE_PIN AD34 [get_ports {dimm1_ddr4_dq[2]}]
set_property PACKAGE_PIN AC33 [get_ports {dimm1_ddr4_dq[3]}]
set_property PACKAGE_PIN AF30 [get_ports {dimm1_ddr4_dq[4]}]
set_property PACKAGE_PIN AE30 [get_ports {dimm1_ddr4_dq[5]}]
set_property PACKAGE_PIN AC32 [get_ports {dimm1_ddr4_dq[6]}]
set_property PACKAGE_PIN AC34 [get_ports {dimm1_ddr4_dq[7]}]
set_property PACKAGE_PIN W30  [get_ports {dimm1_ddr4_dq[8]}]
set_property PACKAGE_PIN W33  [get_ports {dimm1_ddr4_dq[9]}]
set_property PACKAGE_PIN AA34 [get_ports {dimm1_ddr4_dq[10]}]
set_property PACKAGE_PIN AB34 [get_ports {dimm1_ddr4_dq[11]}]
set_property PACKAGE_PIN Y30  [get_ports {dimm1_ddr4_dq[12]}]
set_property PACKAGE_PIN W34  [get_ports {dimm1_ddr4_dq[13]}]
set_property PACKAGE_PIN Y33  [get_ports {dimm1_ddr4_dq[14]}]
set_property PACKAGE_PIN Y32  [get_ports {dimm1_ddr4_dq[15]}]
set_property PACKAGE_PIN AG30 [get_ports {dimm1_ddr4_dq[16]}]
set_property PACKAGE_PIN AJ28 [get_ports {dimm1_ddr4_dq[17]}]
set_property PACKAGE_PIN AJ30 [get_ports {dimm1_ddr4_dq[18]}]
set_property PACKAGE_PIN AK28 [get_ports {dimm1_ddr4_dq[19]}]
set_property PACKAGE_PIN AG29 [get_ports {dimm1_ddr4_dq[20]}]
set_property PACKAGE_PIN AJ31 [get_ports {dimm1_ddr4_dq[21]}]
set_property PACKAGE_PIN AJ29 [get_ports {dimm1_ddr4_dq[22]}]
set_property PACKAGE_PIN AK31 [get_ports {dimm1_ddr4_dq[23]}]
set_property PACKAGE_PIN AL29 [get_ports {dimm1_ddr4_dq[24]}]
set_property PACKAGE_PIN AM31 [get_ports {dimm1_ddr4_dq[25]}]
set_property PACKAGE_PIN AN29 [get_ports {dimm1_ddr4_dq[26]}]
set_property PACKAGE_PIN AP29 [get_ports {dimm1_ddr4_dq[27]}]
set_property PACKAGE_PIN AL30 [get_ports {dimm1_ddr4_dq[28]}]
set_property PACKAGE_PIN AN31 [get_ports {dimm1_ddr4_dq[29]}]
set_property PACKAGE_PIN AP30 [get_ports {dimm1_ddr4_dq[30]}]
set_property PACKAGE_PIN AR30 [get_ports {dimm1_ddr4_dq[31]}]
set_property PACKAGE_PIN BB38 [get_ports {dimm1_ddr4_dq[32]}]
set_property PACKAGE_PIN BC39 [get_ports {dimm1_ddr4_dq[33]}]
set_property PACKAGE_PIN BF38 [get_ports {dimm1_ddr4_dq[34]}]
set_property PACKAGE_PIN BF37 [get_ports {dimm1_ddr4_dq[35]}]
set_property PACKAGE_PIN BC38 [get_ports {dimm1_ddr4_dq[36]}]
set_property PACKAGE_PIN BD39 [get_ports {dimm1_ddr4_dq[37]}]
set_property PACKAGE_PIN BE38 [get_ports {dimm1_ddr4_dq[38]}]
set_property PACKAGE_PIN BE37 [get_ports {dimm1_ddr4_dq[39]}]
set_property PACKAGE_PIN BE33 [get_ports {dimm1_ddr4_dq[40]}]
set_property PACKAGE_PIN BC29 [get_ports {dimm1_ddr4_dq[41]}]
set_property PACKAGE_PIN BE31 [get_ports {dimm1_ddr4_dq[42]}]
set_property PACKAGE_PIN BD29 [get_ports {dimm1_ddr4_dq[43]}]
set_property PACKAGE_PIN BD33 [get_ports {dimm1_ddr4_dq[44]}]
set_property PACKAGE_PIN BE32 [get_ports {dimm1_ddr4_dq[45]}]
set_property PACKAGE_PIN BE30 [get_ports {dimm1_ddr4_dq[46]}]
set_property PACKAGE_PIN BF30 [get_ports {dimm1_ddr4_dq[47]}]
set_property PACKAGE_PIN AV32 [get_ports {dimm1_ddr4_dq[48]}]
set_property PACKAGE_PIN AU32 [get_ports {dimm1_ddr4_dq[49]}]
set_property PACKAGE_PIN AU31 [get_ports {dimm1_ddr4_dq[50]}]
set_property PACKAGE_PIN AT30 [get_ports {dimm1_ddr4_dq[51]}]
set_property PACKAGE_PIN AW31 [get_ports {dimm1_ddr4_dq[52]}]
set_property PACKAGE_PIN AV31 [get_ports {dimm1_ddr4_dq[53]}]
set_property PACKAGE_PIN AU30 [get_ports {dimm1_ddr4_dq[54]}]
set_property PACKAGE_PIN AT29 [get_ports {dimm1_ddr4_dq[55]}]
set_property PACKAGE_PIN AG34 [get_ports {dimm1_ddr4_dq[56]}]
set_property PACKAGE_PIN AG31 [get_ports {dimm1_ddr4_dq[57]}]
set_property PACKAGE_PIN AH33 [get_ports {dimm1_ddr4_dq[58]}]
set_property PACKAGE_PIN AG32 [get_ports {dimm1_ddr4_dq[59]}]
set_property PACKAGE_PIN AF32 [get_ports {dimm1_ddr4_dq[60]}]
set_property PACKAGE_PIN AF34 [get_ports {dimm1_ddr4_dq[61]}]
set_property PACKAGE_PIN AF33 [get_ports {dimm1_ddr4_dq[62]}]
set_property PACKAGE_PIN AJ33 [get_ports {dimm1_ddr4_dq[63]}]
set_property PACKAGE_PIN AY31 [get_ports {dimm1_ddr4_dq[64]}]
set_property PACKAGE_PIN BA29 [get_ports {dimm1_ddr4_dq[65]}]
set_property PACKAGE_PIN BB29 [get_ports {dimm1_ddr4_dq[66]}]
set_property PACKAGE_PIN BB31 [get_ports {dimm1_ddr4_dq[67]}]
set_property PACKAGE_PIN AY30 [get_ports {dimm1_ddr4_dq[68]}]
set_property PACKAGE_PIN AY32 [get_ports {dimm1_ddr4_dq[69]}]
set_property PACKAGE_PIN BA30 [get_ports {dimm1_ddr4_dq[70]}]
set_property PACKAGE_PIN BB30 [get_ports {dimm1_ddr4_dq[71]}]
set_property PACKAGE_PIN AD31 [get_ports {dimm1_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN Y31  [get_ports {dimm1_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN AH29 [get_ports {dimm1_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN AM30 [get_ports {dimm1_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN BE40 [get_ports {dimm1_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN BD31 [get_ports {dimm1_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN AV29 [get_ports {dimm1_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN AH32 [get_ports {dimm1_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN BB32 [get_ports {dimm1_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN AC31 [get_ports {dimm1_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN W31  [get_ports {dimm1_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN AH28 [get_ports {dimm1_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AM29 [get_ports {dimm1_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN BD40 [get_ports {dimm1_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BD30 [get_ports {dimm1_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN AU29 [get_ports {dimm1_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN AH31 [get_ports {dimm1_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN BA32 [get_ports {dimm1_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN BD36 [get_ports {dimm1_ddr4_odt[0]}]
set_property PACKAGE_PIN BD34 [get_ports {dimm1_ddr4_odt[1]}]
set_property PACKAGE_PIN AY36 [get_ports dimm1_ddr4_parity]
set_property PACKAGE_PIN AL33 [get_ports dimm1_ddr4_reset_n]
set_property PACKAGE_PIN BB35 [get_ports dimm1_sys_clk_n]
set_property PACKAGE_PIN BA35 [get_ports dimm1_sys_clk_p]

set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm2_sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm2_sys_clk_p]
set_property IOSTANDARD LVCMOS12        [get_ports dimm2_ddr4_reset_n]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm2_ddr4_dq[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm2_ddr4_dqs_c[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm2_ddr4_dqs_t[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm2_ddr4_ck_c[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm2_ddr4_ck_t[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm2_ddr4_adr[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm2_ddr4_ba[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm2_ddr4_bg[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm2_ddr4_cke[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm2_ddr4_odt[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm2_ddr4_cs_n[*]}]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm2_ddr4_dm_dbi_n[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm2_ddr4_act_n]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm2_ddr4_parity]
set_property SLEW FAST [get_ports {dimm2_ddr4_dq[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_dqs_c[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_dqs_t[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_ck_c[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_ck_t[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_adr[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_ba[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_bg[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_cke[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_odt[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_cs_n[*]}]
set_property SLEW FAST [get_ports {dimm2_ddr4_dm_dbi_n[*]}]
set_property SLEW FAST [get_ports dimm2_ddr4_act_n]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm2_ddr4_dq[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm2_ddr4_dqs_c[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm2_ddr4_dqs_t[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm2_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_dq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_dqs_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_dqs_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_ck_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_ck_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_adr[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_ba[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_bg[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_cke[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_odt[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_cs_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm2_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports dimm2_ddr4_act_n]

set_property PACKAGE_PIN AW16 [get_ports dimm2_ddr4_act_n]
set_property PACKAGE_PIN BB14 [get_ports {dimm2_ddr4_adr[0]}]
set_property PACKAGE_PIN AY11 [get_ports {dimm2_ddr4_adr[1]}]
set_property PACKAGE_PIN AY12 [get_ports {dimm2_ddr4_adr[2]}]
set_property PACKAGE_PIN AY15 [get_ports {dimm2_ddr4_adr[3]}]
set_property PACKAGE_PIN AW13 [get_ports {dimm2_ddr4_adr[4]}]
set_property PACKAGE_PIN AW14 [get_ports {dimm2_ddr4_adr[5]}]
set_property PACKAGE_PIN AY16 [get_ports {dimm2_ddr4_adr[6]}]
set_property PACKAGE_PIN AW15 [get_ports {dimm2_ddr4_adr[7]}]
set_property PACKAGE_PIN AV13 [get_ports {dimm2_ddr4_adr[8]}]
set_property PACKAGE_PIN AU13 [get_ports {dimm2_ddr4_adr[9]}]
set_property PACKAGE_PIN BC14 [get_ports {dimm2_ddr4_adr[10]}]
set_property PACKAGE_PIN AV14 [get_ports {dimm2_ddr4_adr[11]}]
set_property PACKAGE_PIN AU14 [get_ports {dimm2_ddr4_adr[12]}]
set_property PACKAGE_PIN BF14 [get_ports {dimm2_ddr4_adr[13]}]
set_property PACKAGE_PIN BE13 [get_ports {dimm2_ddr4_adr[14]}]
set_property PACKAGE_PIN BD15 [get_ports {dimm2_ddr4_adr[15]}]
set_property PACKAGE_PIN BD14 [get_ports {dimm2_ddr4_adr[16]}]
set_property PACKAGE_PIN BF15 [get_ports {dimm2_ddr4_adr[17]}]
set_property PACKAGE_PIN BD13 [get_ports {dimm2_ddr4_ba[0]}]
set_property PACKAGE_PIN BC13 [get_ports {dimm2_ddr4_ba[1]}]
set_property PACKAGE_PIN AU15 [get_ports {dimm2_ddr4_bg[0]}]
set_property PACKAGE_PIN AT15 [get_ports {dimm2_ddr4_bg[1]}]
set_property PACKAGE_PIN BB12 [get_ports {dimm2_ddr4_ck_c[0]}]
set_property PACKAGE_PIN BA14 [get_ports {dimm2_ddr4_ck_c[1]}]
set_property PACKAGE_PIN AU16 [get_ports {dimm2_ddr4_cke[0]}]
set_property PACKAGE_PIN AV16 [get_ports {dimm2_ddr4_cke[1]}]
set_property PACKAGE_PIN BA12 [get_ports {dimm2_ddr4_ck_t[0]}]
set_property PACKAGE_PIN BA15 [get_ports {dimm2_ddr4_ck_t[1]}]
set_property PACKAGE_PIN BF13 [get_ports {dimm2_ddr4_cs_n[0]}]
set_property PACKAGE_PIN BD16 [get_ports {dimm2_ddr4_cs_n[1]}]
set_property PACKAGE_PIN AV26 [get_ports {dimm2_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN AN22 [get_ports {dimm2_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN AN18 [get_ports {dimm2_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN AV23 [get_ports {dimm2_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN BF24 [get_ports {dimm2_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN BF28 [get_ports {dimm2_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN BA20 [get_ports {dimm2_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN AT19 [get_ports {dimm2_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN BE17 [get_ports {dimm2_ddr4_dm_dbi_n[8]}]
set_property PACKAGE_PIN AT28 [get_ports {dimm2_ddr4_dq[0]}]
set_property PACKAGE_PIN AT27 [get_ports {dimm2_ddr4_dq[1]}]
set_property PACKAGE_PIN AU27 [get_ports {dimm2_ddr4_dq[2]}]
set_property PACKAGE_PIN AU26 [get_ports {dimm2_ddr4_dq[3]}]
set_property PACKAGE_PIN AV28 [get_ports {dimm2_ddr4_dq[4]}]
set_property PACKAGE_PIN AV27 [get_ports {dimm2_ddr4_dq[5]}]
set_property PACKAGE_PIN AR28 [get_ports {dimm2_ddr4_dq[6]}]
set_property PACKAGE_PIN AR27 [get_ports {dimm2_ddr4_dq[7]}]
set_property PACKAGE_PIN AP24 [get_ports {dimm2_ddr4_dq[8]}]
set_property PACKAGE_PIN AN24 [get_ports {dimm2_ddr4_dq[9]}]
set_property PACKAGE_PIN AL22 [get_ports {dimm2_ddr4_dq[10]}]
set_property PACKAGE_PIN AL21 [get_ports {dimm2_ddr4_dq[11]}]
set_property PACKAGE_PIN AP23 [get_ports {dimm2_ddr4_dq[12]}]
set_property PACKAGE_PIN AN23 [get_ports {dimm2_ddr4_dq[13]}]
set_property PACKAGE_PIN AM22 [get_ports {dimm2_ddr4_dq[14]}]
set_property PACKAGE_PIN AM21 [get_ports {dimm2_ddr4_dq[15]}]
set_property PACKAGE_PIN AL20 [get_ports {dimm2_ddr4_dq[16]}]
set_property PACKAGE_PIN AM20 [get_ports {dimm2_ddr4_dq[17]}]
set_property PACKAGE_PIN AM16 [get_ports {dimm2_ddr4_dq[18]}]
set_property PACKAGE_PIN AN19 [get_ports {dimm2_ddr4_dq[19]}]
set_property PACKAGE_PIN AL19 [get_ports {dimm2_ddr4_dq[20]}]
set_property PACKAGE_PIN AM19 [get_ports {dimm2_ddr4_dq[21]}]
set_property PACKAGE_PIN AN16 [get_ports {dimm2_ddr4_dq[22]}]
set_property PACKAGE_PIN AP19 [get_ports {dimm2_ddr4_dq[23]}]
set_property PACKAGE_PIN AT24 [get_ports {dimm2_ddr4_dq[24]}]
set_property PACKAGE_PIN AU22 [get_ports {dimm2_ddr4_dq[25]}]
set_property PACKAGE_PIN AV24 [get_ports {dimm2_ddr4_dq[26]}]
set_property PACKAGE_PIN AW24 [get_ports {dimm2_ddr4_dq[27]}]
set_property PACKAGE_PIN AR23 [get_ports {dimm2_ddr4_dq[28]}]
set_property PACKAGE_PIN AT23 [get_ports {dimm2_ddr4_dq[29]}]
set_property PACKAGE_PIN AU24 [get_ports {dimm2_ddr4_dq[30]}]
set_property PACKAGE_PIN AV22 [get_ports {dimm2_ddr4_dq[31]}]
set_property PACKAGE_PIN BD20 [get_ports {dimm2_ddr4_dq[32]}]
set_property PACKAGE_PIN BE20 [get_ports {dimm2_ddr4_dq[33]}]
set_property PACKAGE_PIN BE21 [get_ports {dimm2_ddr4_dq[34]}]
set_property PACKAGE_PIN BE23 [get_ports {dimm2_ddr4_dq[35]}]
set_property PACKAGE_PIN BC24 [get_ports {dimm2_ddr4_dq[36]}]
set_property PACKAGE_PIN BD21 [get_ports {dimm2_ddr4_dq[37]}]
set_property PACKAGE_PIN BD23 [get_ports {dimm2_ddr4_dq[38]}]
set_property PACKAGE_PIN BD24 [get_ports {dimm2_ddr4_dq[39]}]
set_property PACKAGE_PIN BC26 [get_ports {dimm2_ddr4_dq[40]}]
set_property PACKAGE_PIN BE25 [get_ports {dimm2_ddr4_dq[41]}]
set_property PACKAGE_PIN BE27 [get_ports {dimm2_ddr4_dq[42]}]
set_property PACKAGE_PIN BF27 [get_ports {dimm2_ddr4_dq[43]}]
set_property PACKAGE_PIN BF25 [get_ports {dimm2_ddr4_dq[44]}]
set_property PACKAGE_PIN BC27 [get_ports {dimm2_ddr4_dq[45]}]
set_property PACKAGE_PIN BD28 [get_ports {dimm2_ddr4_dq[46]}]
set_property PACKAGE_PIN BE28 [get_ports {dimm2_ddr4_dq[47]}]
set_property PACKAGE_PIN BC21 [get_ports {dimm2_ddr4_dq[48]}]
set_property PACKAGE_PIN BB21 [get_ports {dimm2_ddr4_dq[49]}]
set_property PACKAGE_PIN BA22 [get_ports {dimm2_ddr4_dq[50]}]
set_property PACKAGE_PIN BA23 [get_ports {dimm2_ddr4_dq[51]}]
set_property PACKAGE_PIN BC22 [get_ports {dimm2_ddr4_dq[52]}]
set_property PACKAGE_PIN BB22 [get_ports {dimm2_ddr4_dq[53]}]
set_property PACKAGE_PIN AY23 [get_ports {dimm2_ddr4_dq[54]}]
set_property PACKAGE_PIN AY22 [get_ports {dimm2_ddr4_dq[55]}]
set_property PACKAGE_PIN AP18 [get_ports {dimm2_ddr4_dq[56]}]
set_property PACKAGE_PIN AR18 [get_ports {dimm2_ddr4_dq[57]}]
set_property PACKAGE_PIN AT18 [get_ports {dimm2_ddr4_dq[58]}]
set_property PACKAGE_PIN AU17 [get_ports {dimm2_ddr4_dq[59]}]
set_property PACKAGE_PIN AP20 [get_ports {dimm2_ddr4_dq[60]}]
set_property PACKAGE_PIN AR20 [get_ports {dimm2_ddr4_dq[61]}]
set_property PACKAGE_PIN AT20 [get_ports {dimm2_ddr4_dq[62]}]
set_property PACKAGE_PIN AU20 [get_ports {dimm2_ddr4_dq[63]}]
set_property PACKAGE_PIN BC17 [get_ports {dimm2_ddr4_dq[64]}]
set_property PACKAGE_PIN BC18 [get_ports {dimm2_ddr4_dq[65]}]
set_property PACKAGE_PIN BE18 [get_ports {dimm2_ddr4_dq[66]}]
set_property PACKAGE_PIN BB19 [get_ports {dimm2_ddr4_dq[67]}]
set_property PACKAGE_PIN BB17 [get_ports {dimm2_ddr4_dq[68]}]
set_property PACKAGE_PIN BD18 [get_ports {dimm2_ddr4_dq[69]}]
set_property PACKAGE_PIN BF18 [get_ports {dimm2_ddr4_dq[70]}]
set_property PACKAGE_PIN BF19 [get_ports {dimm2_ddr4_dq[71]}]
set_property PACKAGE_PIN AT25 [get_ports {dimm2_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN AM24 [get_ports {dimm2_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN AM17 [get_ports {dimm2_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN AT22 [get_ports {dimm2_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN BF22 [get_ports {dimm2_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN BE26 [get_ports {dimm2_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN BB24 [get_ports {dimm2_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN AT17 [get_ports {dimm2_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN BD19 [get_ports {dimm2_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN AR25 [get_ports {dimm2_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AL24 [get_ports {dimm2_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN AL17 [get_ports {dimm2_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AR22 [get_ports {dimm2_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN BE22 [get_ports {dimm2_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BD26 [get_ports {dimm2_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN BA24 [get_ports {dimm2_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN AR17 [get_ports {dimm2_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN BC19 [get_ports {dimm2_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN BE15 [get_ports {dimm2_ddr4_odt[0]}]
set_property PACKAGE_PIN BE16 [get_ports {dimm2_ddr4_odt[1]}]
set_property PACKAGE_PIN BB15 [get_ports dimm2_ddr4_parity]
set_property PACKAGE_PIN AT13 [get_ports dimm2_ddr4_reset_n]
set_property PACKAGE_PIN AW19 [get_ports dimm2_sys_clk_n]
set_property PACKAGE_PIN AV19 [get_ports dimm2_sys_clk_p]

set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm3_sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12     [get_ports dimm3_sys_clk_p]
set_property IOSTANDARD LVCMOS12        [get_ports dimm3_ddr4_reset_n]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm3_ddr4_dq[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm3_ddr4_dqs_c[*]}]
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {dimm3_ddr4_dqs_t[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm3_ddr4_ck_c[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {dimm3_ddr4_ck_t[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm3_ddr4_adr[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm3_ddr4_ba[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm3_ddr4_bg[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm3_ddr4_cke[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm3_ddr4_odt[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {dimm3_ddr4_cs_n[*]}]
set_property IOSTANDARD POD12_DCI       [get_ports {dimm3_ddr4_dm_dbi_n[*]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm3_ddr4_act_n]
set_property IOSTANDARD SSTL12_DCI      [get_ports dimm3_ddr4_parity]
set_property SLEW FAST [get_ports {dimm3_ddr4_dq[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_dqs_c[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_dqs_t[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_ck_c[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_ck_t[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_adr[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_ba[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_bg[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_cke[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_odt[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_cs_n[*]}]
set_property SLEW FAST [get_ports {dimm3_ddr4_dm_dbi_n[*]}]
set_property SLEW FAST [get_ports dimm3_ddr4_act_n]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm3_ddr4_dq[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm3_ddr4_dqs_c[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm3_ddr4_dqs_t[*]}]
set_property IBUF_LOW_PWR FALSE [get_ports {dimm3_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_dq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_dqs_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_dqs_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_ck_c[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_ck_t[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_adr[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_ba[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_bg[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_cke[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_odt[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_cs_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {dimm3_ddr4_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports dimm3_ddr4_act_n]

set_property PACKAGE_PIN D15 [get_ports dimm3_ddr4_act_n]
set_property PACKAGE_PIN N13 [get_ports {dimm3_ddr4_adr[0]}]
set_property PACKAGE_PIN J13 [get_ports {dimm3_ddr4_adr[1]}]
set_property PACKAGE_PIN H16 [get_ports {dimm3_ddr4_adr[2]}]
set_property PACKAGE_PIN H13 [get_ports {dimm3_ddr4_adr[3]}]
set_property PACKAGE_PIN G14 [get_ports {dimm3_ddr4_adr[4]}]
set_property PACKAGE_PIN G15 [get_ports {dimm3_ddr4_adr[5]}]
set_property PACKAGE_PIN H17 [get_ports {dimm3_ddr4_adr[6]}]
set_property PACKAGE_PIN F14 [get_ports {dimm3_ddr4_adr[7]}]
set_property PACKAGE_PIN F13 [get_ports {dimm3_ddr4_adr[8]}]
set_property PACKAGE_PIN G16 [get_ports {dimm3_ddr4_adr[9]}]
set_property PACKAGE_PIN K15 [get_ports {dimm3_ddr4_adr[10]}]
set_property PACKAGE_PIN E13 [get_ports {dimm3_ddr4_adr[11]}]
set_property PACKAGE_PIN F15 [get_ports {dimm3_ddr4_adr[12]}]
set_property PACKAGE_PIN R15 [get_ports {dimm3_ddr4_adr[13]}]
set_property PACKAGE_PIN P13 [get_ports {dimm3_ddr4_adr[14]}]
set_property PACKAGE_PIN P14 [get_ports {dimm3_ddr4_adr[15]}]
set_property PACKAGE_PIN K16 [get_ports {dimm3_ddr4_adr[16]}]
set_property PACKAGE_PIN P15 [get_ports {dimm3_ddr4_adr[17]}]
set_property PACKAGE_PIN N14 [get_ports {dimm3_ddr4_ba[0]}]
set_property PACKAGE_PIN M14 [get_ports {dimm3_ddr4_ba[1]}]
set_property PACKAGE_PIN E15 [get_ports {dimm3_ddr4_bg[0]}]
set_property PACKAGE_PIN G17 [get_ports {dimm3_ddr4_bg[1]}]
set_property PACKAGE_PIN K13 [get_ports {dimm3_ddr4_ck_c[0]}]
set_property PACKAGE_PIN H14 [get_ports {dimm3_ddr4_ck_c[1]}]
set_property PACKAGE_PIN D16 [get_ports {dimm3_ddr4_cke[0]}]
set_property PACKAGE_PIN E16 [get_ports {dimm3_ddr4_cke[1]}]
set_property PACKAGE_PIN L13 [get_ports {dimm3_ddr4_ck_t[0]}]
set_property PACKAGE_PIN J14 [get_ports {dimm3_ddr4_ck_t[1]}]
set_property PACKAGE_PIN M16 [get_ports {dimm3_ddr4_cs_n[0]}]
set_property PACKAGE_PIN P16 [get_ports {dimm3_ddr4_cs_n[1]}]
set_property PACKAGE_PIN H19 [get_ports {dimm3_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN L17 [get_ports {dimm3_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN L25 [get_ports {dimm3_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN C22 [get_ports {dimm3_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN D13 [get_ports {dimm3_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN G25 [get_ports {dimm3_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN N17 [get_ports {dimm3_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN R21 [get_ports {dimm3_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN D19 [get_ports {dimm3_ddr4_dm_dbi_n[8]}]
set_property PACKAGE_PIN G20 [get_ports {dimm3_ddr4_dq[0]}]
set_property PACKAGE_PIN E21 [get_ports {dimm3_ddr4_dq[1]}]
set_property PACKAGE_PIN F20 [get_ports {dimm3_ddr4_dq[2]}]
set_property PACKAGE_PIN E20 [get_ports {dimm3_ddr4_dq[3]}]
set_property PACKAGE_PIN G19 [get_ports {dimm3_ddr4_dq[4]}]
set_property PACKAGE_PIN F17 [get_ports {dimm3_ddr4_dq[5]}]
set_property PACKAGE_PIN F18 [get_ports {dimm3_ddr4_dq[6]}]
set_property PACKAGE_PIN F19 [get_ports {dimm3_ddr4_dq[7]}]
set_property PACKAGE_PIN J20 [get_ports {dimm3_ddr4_dq[8]}]
set_property PACKAGE_PIN J19 [get_ports {dimm3_ddr4_dq[9]}]
set_property PACKAGE_PIN L18 [get_ports {dimm3_ddr4_dq[10]}]
set_property PACKAGE_PIN L19 [get_ports {dimm3_ddr4_dq[11]}]
set_property PACKAGE_PIN J18 [get_ports {dimm3_ddr4_dq[12]}]
set_property PACKAGE_PIN K18 [get_ports {dimm3_ddr4_dq[13]}]
set_property PACKAGE_PIN K20 [get_ports {dimm3_ddr4_dq[14]}]
set_property PACKAGE_PIN L20 [get_ports {dimm3_ddr4_dq[15]}]
set_property PACKAGE_PIN L23 [get_ports {dimm3_ddr4_dq[16]}]
set_property PACKAGE_PIN K23 [get_ports {dimm3_ddr4_dq[17]}]
set_property PACKAGE_PIN J24 [get_ports {dimm3_ddr4_dq[18]}]
set_property PACKAGE_PIN H24 [get_ports {dimm3_ddr4_dq[19]}]
set_property PACKAGE_PIN L22 [get_ports {dimm3_ddr4_dq[20]}]
set_property PACKAGE_PIN K22 [get_ports {dimm3_ddr4_dq[21]}]
set_property PACKAGE_PIN J23 [get_ports {dimm3_ddr4_dq[22]}]
set_property PACKAGE_PIN H23 [get_ports {dimm3_ddr4_dq[23]}]
set_property PACKAGE_PIN A25 [get_ports {dimm3_ddr4_dq[24]}]
set_property PACKAGE_PIN B26 [get_ports {dimm3_ddr4_dq[25]}]
set_property PACKAGE_PIN B24 [get_ports {dimm3_ddr4_dq[26]}]
set_property PACKAGE_PIN A24 [get_ports {dimm3_ddr4_dq[27]}]
set_property PACKAGE_PIN C26 [get_ports {dimm3_ddr4_dq[28]}]
set_property PACKAGE_PIN B25 [get_ports {dimm3_ddr4_dq[29]}]
set_property PACKAGE_PIN C24 [get_ports {dimm3_ddr4_dq[30]}]
set_property PACKAGE_PIN C23 [get_ports {dimm3_ddr4_dq[31]}]
set_property PACKAGE_PIN A17 [get_ports {dimm3_ddr4_dq[32]}]
set_property PACKAGE_PIN B17 [get_ports {dimm3_ddr4_dq[33]}]
set_property PACKAGE_PIN A13 [get_ports {dimm3_ddr4_dq[34]}]
set_property PACKAGE_PIN B14 [get_ports {dimm3_ddr4_dq[35]}]
set_property PACKAGE_PIN A14 [get_ports {dimm3_ddr4_dq[36]}]
set_property PACKAGE_PIN B16 [get_ports {dimm3_ddr4_dq[37]}]
set_property PACKAGE_PIN C14 [get_ports {dimm3_ddr4_dq[38]}]
set_property PACKAGE_PIN C16 [get_ports {dimm3_ddr4_dq[39]}]
set_property PACKAGE_PIN D23 [get_ports {dimm3_ddr4_dq[40]}]
set_property PACKAGE_PIN D25 [get_ports {dimm3_ddr4_dq[41]}]
set_property PACKAGE_PIN F24 [get_ports {dimm3_ddr4_dq[42]}]
set_property PACKAGE_PIN F23 [get_ports {dimm3_ddr4_dq[43]}]
set_property PACKAGE_PIN D24 [get_ports {dimm3_ddr4_dq[44]}]
set_property PACKAGE_PIN F22 [get_ports {dimm3_ddr4_dq[45]}]
set_property PACKAGE_PIN G22 [get_ports {dimm3_ddr4_dq[46]}]
set_property PACKAGE_PIN E25 [get_ports {dimm3_ddr4_dq[47]}]
set_property PACKAGE_PIN M20 [get_ports {dimm3_ddr4_dq[48]}]
set_property PACKAGE_PIN M19 [get_ports {dimm3_ddr4_dq[49]}]
set_property PACKAGE_PIN N18 [get_ports {dimm3_ddr4_dq[50]}]
set_property PACKAGE_PIN P18 [get_ports {dimm3_ddr4_dq[51]}]
set_property PACKAGE_PIN M21 [get_ports {dimm3_ddr4_dq[52]}]
set_property PACKAGE_PIN N21 [get_ports {dimm3_ddr4_dq[53]}]
set_property PACKAGE_PIN P20 [get_ports {dimm3_ddr4_dq[54]}]
set_property PACKAGE_PIN R20 [get_ports {dimm3_ddr4_dq[55]}]
set_property PACKAGE_PIN M22 [get_ports {dimm3_ddr4_dq[56]}]
set_property PACKAGE_PIN N22 [get_ports {dimm3_ddr4_dq[57]}]
set_property PACKAGE_PIN M24 [get_ports {dimm3_ddr4_dq[58]}]
set_property PACKAGE_PIN P25 [get_ports {dimm3_ddr4_dq[59]}]
set_property PACKAGE_PIN N23 [get_ports {dimm3_ddr4_dq[60]}]
set_property PACKAGE_PIN P23 [get_ports {dimm3_ddr4_dq[61]}]
set_property PACKAGE_PIN M25 [get_ports {dimm3_ddr4_dq[62]}]
set_property PACKAGE_PIN R25 [get_ports {dimm3_ddr4_dq[63]}]
set_property PACKAGE_PIN C21 [get_ports {dimm3_ddr4_dq[64]}]
set_property PACKAGE_PIN A20 [get_ports {dimm3_ddr4_dq[65]}]
set_property PACKAGE_PIN B20 [get_ports {dimm3_ddr4_dq[66]}]
set_property PACKAGE_PIN B19 [get_ports {dimm3_ddr4_dq[67]}]
set_property PACKAGE_PIN B21 [get_ports {dimm3_ddr4_dq[68]}]
set_property PACKAGE_PIN D21 [get_ports {dimm3_ddr4_dq[69]}]
set_property PACKAGE_PIN D20 [get_ports {dimm3_ddr4_dq[70]}]
set_property PACKAGE_PIN A19 [get_ports {dimm3_ddr4_dq[71]}]
set_property PACKAGE_PIN E17 [get_ports {dimm3_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN H21 [get_ports {dimm3_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN J25 [get_ports {dimm3_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN A22 [get_ports {dimm3_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN A15 [get_ports {dimm3_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN E22 [get_ports {dimm3_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN N19 [get_ports {dimm3_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN N24 [get_ports {dimm3_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN C18 [get_ports {dimm3_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN E18 [get_ports {dimm3_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN J21 [get_ports {dimm3_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN K25 [get_ports {dimm3_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN A23 [get_ports {dimm3_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN B15 [get_ports {dimm3_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN E23 [get_ports {dimm3_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN P19 [get_ports {dimm3_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN P24 [get_ports {dimm3_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN D18 [get_ports {dimm3_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN N16 [get_ports {dimm3_ddr4_odt[0]}]
set_property PACKAGE_PIN R16 [get_ports {dimm3_ddr4_odt[1]}]
set_property PACKAGE_PIN L14 [get_ports dimm3_ddr4_parity]
set_property PACKAGE_PIN C17 [get_ports dimm3_ddr4_reset_n]
set_property PACKAGE_PIN J15 [get_ports dimm3_sys_clk_n]
set_property PACKAGE_PIN J16 [get_ports dimm3_sys_clk_p]

# Reserved Pins
set_property PACKAGE_PIN AV21 [get_ports reserved_in[0]]
set_property PACKAGE_PIN AW21 [get_ports reserved_in[1]]
set_property PACKAGE_PIN AV18 [get_ports reserved_in[2]]
set_property PACKAGE_PIN AW18 [get_ports reserved_in[3]]
set_property IOSTANDARD DIFF_SSTL12 [get_ports reserved_in[*]]

set_property PACKAGE_PIN AW20 [get_ports reserved_out[0]]
set_property IOSTANDARD LVCMOS12 [get_ports reserved_out[*]]
set_property SLEW SLOW [get_ports reserved_out[*]]
set_property DRIVE 4   [get_ports reserved_out[*]]

set_property PACKAGE_PIN AY17 [get_ports reserved_inout[0]]
set_property PACKAGE_PIN BA17 [get_ports reserved_inout[1]]
set_property PACKAGE_PIN AY18 [get_ports reserved_inout[2]]
set_property PACKAGE_PIN BA18 [get_ports reserved_inout[3]]
set_property IOSTANDARD LVCMOS12 [get_ports reserved_inout[*]]
set_property SLEW SLOW [get_ports reserved_inout[*]]
set_property DRIVE 4   [get_ports reserved_inout[*]]

