#-------------------------------------------------------------------------------
#- Copyright (c) 2026 Arista Networks, Inc. All rights reserved.
#-------------------------------------------------------------------------------
#- Maintainers:
#-   fdk-support@arista.com
#-
#- Description:
#-
#- Tags:
#-
#-------------------------------------------------------------------------------
#Tags
#license-bsd-3-clause
#-----------------------------------------------------------
# Arista Networks, Inc. Confidential and Proprietary.
# Copyright (c) 2026 Arista Networks, Inc. All rights reserved.
# DO NOT EDIT THIS FILE!!!!! This is an auto-generated file.
#-----------------------------------------------------------

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# direction INPUT timesync_clk_p
create_clock -period 100.0 -name timesync_clk_p [get_ports timesync_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports timesync_clk_p]
set_property PACKAGE_PIN BT25 [get_ports timesync_clk_p]

# direction INPUT timesync_clk_n
set_property IOSTANDARD DIFF_SSTL12 [get_ports timesync_clk_n]
set_property PACKAGE_PIN BU25 [get_ports timesync_clk_n]

# direction INPUT pps_in
set_property IOSTANDARD LVCMOS12 [get_ports pps_in]
set_property PACKAGE_PIN BH25 [get_ports pps_in]

# direction OUTPUT pps_out
set_property IOSTANDARD LVCMOS12 [get_ports pps_out]
set_property PACKAGE_PIN BP25 [get_ports pps_out]

# direction INPUT sync_in_p
set_property IOSTANDARD DIFF_SSTL12 [get_ports sync_in_p]
set_property PACKAGE_PIN BL25 [get_ports sync_in_p]

# direction INPUT sync_in_n
set_property IOSTANDARD DIFF_SSTL12 [get_ports sync_in_n]
set_property PACKAGE_PIN BM25 [get_ports sync_in_n]

# direction OUTPUT sync_out_p
set_property IOSTANDARD DIFF_SSTL12 [get_ports sync_out_p]
set_property PACKAGE_PIN BU29 [get_ports sync_out_p]

# direction OUTPUT sync_out_n
set_property IOSTANDARD DIFF_SSTL12 [get_ports sync_out_n]
set_property PACKAGE_PIN BV29 [get_ports sync_out_n]

# direction INPUT fabric_refclk_p[0]
create_clock -period 8.0 -name fabric_refclk_p_0 [get_ports fabric_refclk_p[0]]
set_property IOSTANDARD DIFF_SSTL12 [get_ports fabric_refclk_p[0]]
set_property PACKAGE_PIN BV34 [get_ports fabric_refclk_p[0]]

# direction INPUT fabric_refclk_n[0]
set_property IOSTANDARD DIFF_SSTL12 [get_ports fabric_refclk_n[0]]
set_property PACKAGE_PIN BW34 [get_ports fabric_refclk_n[0]]

# direction INPUT fabric_refclk_p[1]
create_clock -period 6.206 -name fabric_refclk_p_1 [get_ports fabric_refclk_p[1]]
set_property IOSTANDARD DIFF_SSTL12 [get_ports fabric_refclk_p[1]]
set_property PACKAGE_PIN BT33 [get_ports fabric_refclk_p[1]]

# direction INPUT fabric_refclk_n[1]
set_property IOSTANDARD DIFF_SSTL12 [get_ports fabric_refclk_n[1]]
set_property PACKAGE_PIN BT34 [get_ports fabric_refclk_n[1]]

# direction OUTPUT refclk_out_p
set_property IOSTANDARD DIFF_SSTL12 [get_ports refclk_out_p]
set_property PACKAGE_PIN BT32 [get_ports refclk_out_p]

# direction OUTPUT refclk_out_n
set_property IOSTANDARD DIFF_SSTL12 [get_ports refclk_out_n]
set_property PACKAGE_PIN BU32 [get_ports refclk_out_n]

# direction INPUT gt_refclk_p[0]
create_clock -period 6.206 -name gt_refclk_p_0 [get_ports gt_refclk_p[0]]
set_property PACKAGE_PIN AF9 [get_ports gt_refclk_p[0]]

# direction INPUT gt_refclk_p[2]
create_clock -period 6.206 -name gt_refclk_p_2 [get_ports gt_refclk_p[2]]
set_property PACKAGE_PIN AD9 [get_ports gt_refclk_p[2]]

# direction INPUT gt_refclk_p[4]
create_clock -period 6.206 -name gt_refclk_p_4 [get_ports gt_refclk_p[4]]
set_property PACKAGE_PIN Y9 [get_ports gt_refclk_p[4]]

# direction INPUT gt_refclk_p[6]
create_clock -period 6.206 -name gt_refclk_p_6 [get_ports gt_refclk_p[6]]
set_property PACKAGE_PIN BG45 [get_ports gt_refclk_p[6]]

# direction INPUT gt_refclk_p[8]
create_clock -period 6.206 -name gt_refclk_p_8 [get_ports gt_refclk_p[8]]
set_property PACKAGE_PIN AM47 [get_ports gt_refclk_p[8]]

# direction INPUT gt_refclk_p[10]
create_clock -period 6.206 -name gt_refclk_p_10 [get_ports gt_refclk_p[10]]
set_property PACKAGE_PIN AJ49 [get_ports gt_refclk_p[10]]

# direction INPUT gt_refclk_p[12]
create_clock -period 6.206 -name gt_refclk_p_12 [get_ports gt_refclk_p[12]]
set_property PACKAGE_PIN AG49 [get_ports gt_refclk_p[12]]

# direction INPUT gt_refclk_p[14]
create_clock -period 6.206 -name gt_refclk_p_14 [get_ports gt_refclk_p[14]]
set_property PACKAGE_PIN AW45 [get_ports gt_refclk_p[14]]

# direction INPUT gt_refclk_p[16]
create_clock -period 6.206 -name gt_refclk_p_16 [get_ports gt_refclk_p[16]]
set_property PACKAGE_PIN AR49 [get_ports gt_refclk_p[16]]

# direction INPUT gt_refclk_n[0]
set_property PACKAGE_PIN AF8 [get_ports gt_refclk_n[0]]

# direction INPUT gt_refclk_n[2]
set_property PACKAGE_PIN AD8 [get_ports gt_refclk_n[2]]

# direction INPUT gt_refclk_n[4]
set_property PACKAGE_PIN Y8 [get_ports gt_refclk_n[4]]

# direction INPUT gt_refclk_n[6]
set_property PACKAGE_PIN BG46 [get_ports gt_refclk_n[6]]

# direction INPUT gt_refclk_n[8]
set_property PACKAGE_PIN AM48 [get_ports gt_refclk_n[8]]

# direction INPUT gt_refclk_n[10]
set_property PACKAGE_PIN AJ50 [get_ports gt_refclk_n[10]]

# direction INPUT gt_refclk_n[12]
set_property PACKAGE_PIN AG50 [get_ports gt_refclk_n[12]]

# direction INPUT gt_refclk_n[14]
set_property PACKAGE_PIN AW46 [get_ports gt_refclk_n[14]]

# direction INPUT gt_refclk_n[16]
set_property PACKAGE_PIN AR50 [get_ports gt_refclk_n[16]]

# direction INPUT gt_refclk_p[1]
create_clock -period 8.0 -name gt_refclk_p_1 [get_ports gt_refclk_p[1]]
set_property PACKAGE_PIN AE7 [get_ports gt_refclk_p[1]]

# direction INPUT gt_refclk_p[3]
create_clock -period 8.0 -name gt_refclk_p_3 [get_ports gt_refclk_p[3]]
set_property PACKAGE_PIN AA7 [get_ports gt_refclk_p[3]]

# direction INPUT gt_refclk_p[5]
create_clock -period 8.0 -name gt_refclk_p_5 [get_ports gt_refclk_p[5]]
set_property PACKAGE_PIN R7 [get_ports gt_refclk_p[5]]

# direction INPUT gt_refclk_p[7]
create_clock -period 8.0 -name gt_refclk_p_7 [get_ports gt_refclk_p[7]]
set_property PACKAGE_PIN BB47 [get_ports gt_refclk_p[7]]

# direction INPUT gt_refclk_p[9]
create_clock -period 8.0 -name gt_refclk_p_9 [get_ports gt_refclk_p[9]]
set_property PACKAGE_PIN AK47 [get_ports gt_refclk_p[9]]

# direction INPUT gt_refclk_p[11]
create_clock -period 8.0 -name gt_refclk_p_11 [get_ports gt_refclk_p[11]]
set_property PACKAGE_PIN AH47 [get_ports gt_refclk_p[11]]

# direction INPUT gt_refclk_p[13]
create_clock -period 8.0 -name gt_refclk_p_13 [get_ports gt_refclk_p[13]]
set_property PACKAGE_PIN AF47 [get_ports gt_refclk_p[13]]

# direction INPUT gt_refclk_p[15]
create_clock -period 8.0 -name gt_refclk_p_15 [get_ports gt_refclk_p[15]]
set_property PACKAGE_PIN AT47 [get_ports gt_refclk_p[15]]

# direction INPUT gt_refclk_p[17]
create_clock -period 8.0 -name gt_refclk_p_17 [get_ports gt_refclk_p[17]]
set_property PACKAGE_PIN AN49 [get_ports gt_refclk_p[17]]

# direction INPUT gt_refclk_n[1]
set_property PACKAGE_PIN AE6 [get_ports gt_refclk_n[1]]

# direction INPUT gt_refclk_n[3]
set_property PACKAGE_PIN AA6 [get_ports gt_refclk_n[3]]

# direction INPUT gt_refclk_n[5]
set_property PACKAGE_PIN R6 [get_ports gt_refclk_n[5]]

# direction INPUT gt_refclk_n[7]
set_property PACKAGE_PIN BB48 [get_ports gt_refclk_n[7]]

# direction INPUT gt_refclk_n[9]
set_property PACKAGE_PIN AK48 [get_ports gt_refclk_n[9]]

# direction INPUT gt_refclk_n[11]
set_property PACKAGE_PIN AH48 [get_ports gt_refclk_n[11]]

# direction INPUT gt_refclk_n[13]
set_property PACKAGE_PIN AF48 [get_ports gt_refclk_n[13]]

# direction INPUT gt_refclk_n[15]
set_property PACKAGE_PIN AT48 [get_ports gt_refclk_n[15]]

# direction INPUT gt_refclk_n[17]
set_property PACKAGE_PIN AN50 [get_ports gt_refclk_n[17]]

# direction INPUT gt_rx_p[1]
set_property PACKAGE_PIN D8 [get_ports gt_rx_p[1]]

# direction INPUT gt_rx_p[2]
set_property PACKAGE_PIN B9 [get_ports gt_rx_p[2]]

# direction INPUT gt_rx_p[3]
set_property PACKAGE_PIN F9 [get_ports gt_rx_p[3]]

# direction INPUT gt_rx_p[4]
set_property PACKAGE_PIN D10 [get_ports gt_rx_p[4]]

# direction INPUT gt_rx_p[5]
set_property PACKAGE_PIN B11 [get_ports gt_rx_p[5]]

# direction INPUT gt_rx_p[6]
set_property PACKAGE_PIN F11 [get_ports gt_rx_p[6]]

# direction INPUT gt_rx_p[7]
set_property PACKAGE_PIN D12 [get_ports gt_rx_p[7]]

# direction INPUT gt_rx_p[8]
set_property PACKAGE_PIN B13 [get_ports gt_rx_p[8]]

# direction INPUT gt_rx_p[9]
set_property PACKAGE_PIN F13 [get_ports gt_rx_p[9]]

# direction INPUT gt_rx_p[10]
set_property PACKAGE_PIN D14 [get_ports gt_rx_p[10]]

# direction INPUT gt_rx_p[11]
set_property PACKAGE_PIN B15 [get_ports gt_rx_p[11]]

# direction INPUT gt_rx_p[12]
set_property PACKAGE_PIN F15 [get_ports gt_rx_p[12]]

# direction INPUT gt_rx_p[13]
set_property PACKAGE_PIN D16 [get_ports gt_rx_p[13]]

# direction INPUT gt_rx_p[14]
set_property PACKAGE_PIN B17 [get_ports gt_rx_p[14]]

# direction INPUT gt_rx_p[15]
set_property PACKAGE_PIN F17 [get_ports gt_rx_p[15]]

# direction INPUT gt_rx_p[16]
set_property PACKAGE_PIN D18 [get_ports gt_rx_p[16]]

# direction INPUT gt_rx_p[17]
set_property PACKAGE_PIN B19 [get_ports gt_rx_p[17]]

# direction INPUT gt_rx_p[18]
set_property PACKAGE_PIN F19 [get_ports gt_rx_p[18]]

# direction INPUT gt_rx_p[19]
set_property PACKAGE_PIN D20 [get_ports gt_rx_p[19]]

# direction INPUT gt_rx_p[20]
set_property PACKAGE_PIN B21 [get_ports gt_rx_p[20]]

# direction INPUT gt_rx_p[21]
set_property PACKAGE_PIN BE58 [get_ports gt_rx_p[21]]

# direction INPUT gt_rx_p[22]
set_property PACKAGE_PIN BD60 [get_ports gt_rx_p[22]]

# direction INPUT gt_rx_p[23]
set_property PACKAGE_PIN BC58 [get_ports gt_rx_p[23]]

# direction INPUT gt_rx_p[24]
set_property PACKAGE_PIN BB60 [get_ports gt_rx_p[24]]

# direction INPUT gt_rx_p[25]
set_property PACKAGE_PIN BB56 [get_ports gt_rx_p[25]]

# direction INPUT gt_rx_p[26]
set_property PACKAGE_PIN BA58 [get_ports gt_rx_p[26]]

# direction INPUT gt_rx_p[27]
set_property PACKAGE_PIN AY60 [get_ports gt_rx_p[27]]

# direction INPUT gt_rx_p[28]
set_property PACKAGE_PIN AW58 [get_ports gt_rx_p[28]]

# direction INPUT gt_rx_p[29]
set_property PACKAGE_PIN F61 [get_ports gt_rx_p[29]]

# direction INPUT gt_rx_p[30]
set_property PACKAGE_PIN F59 [get_ports gt_rx_p[30]]

# direction INPUT gt_rx_p[31]
set_property PACKAGE_PIN D58 [get_ports gt_rx_p[31]]

# direction INPUT gt_rx_p[32]
set_property PACKAGE_PIN B57 [get_ports gt_rx_p[32]]

# direction INPUT gt_rx_p[33]
set_property PACKAGE_PIN F57 [get_ports gt_rx_p[33]]

# direction INPUT gt_rx_p[34]
set_property PACKAGE_PIN D56 [get_ports gt_rx_p[34]]

# direction INPUT gt_rx_p[35]
set_property PACKAGE_PIN B55 [get_ports gt_rx_p[35]]

# direction INPUT gt_rx_p[36]
set_property PACKAGE_PIN F55 [get_ports gt_rx_p[36]]

# direction INPUT gt_rx_p[37]
set_property PACKAGE_PIN D54 [get_ports gt_rx_p[37]]

# direction INPUT gt_rx_p[38]
set_property PACKAGE_PIN B53 [get_ports gt_rx_p[38]]

# direction INPUT gt_rx_p[39]
set_property PACKAGE_PIN F53 [get_ports gt_rx_p[39]]

# direction INPUT gt_rx_p[40]
set_property PACKAGE_PIN D52 [get_ports gt_rx_p[40]]

# direction INPUT gt_rx_p[41]
set_property PACKAGE_PIN B51 [get_ports gt_rx_p[41]]

# direction INPUT gt_rx_p[42]
set_property PACKAGE_PIN F51 [get_ports gt_rx_p[42]]

# direction INPUT gt_rx_p[43]
set_property PACKAGE_PIN D50 [get_ports gt_rx_p[43]]

# direction INPUT gt_rx_p[44]
set_property PACKAGE_PIN B49 [get_ports gt_rx_p[44]]

# direction INPUT gt_rx_p[45]
set_property PACKAGE_PIN F49 [get_ports gt_rx_p[45]]

# direction INPUT gt_rx_p[46]
set_property PACKAGE_PIN D48 [get_ports gt_rx_p[46]]

# direction INPUT gt_rx_p[47]
set_property PACKAGE_PIN B47 [get_ports gt_rx_p[47]]

# direction INPUT gt_rx_p[48]
set_property PACKAGE_PIN F47 [get_ports gt_rx_p[48]]

# direction INPUT gt_rx_p[49]
set_property PACKAGE_PIN D46 [get_ports gt_rx_p[49]]

# direction INPUT gt_rx_p[50]
set_property PACKAGE_PIN B45 [get_ports gt_rx_p[50]]

# direction INPUT gt_rx_p[51]
set_property PACKAGE_PIN F45 [get_ports gt_rx_p[51]]

# direction INPUT gt_rx_p[52]
set_property PACKAGE_PIN D44 [get_ports gt_rx_p[52]]

# direction INPUT gt_rx_p[53]
set_property PACKAGE_PIN AN57 [get_ports gt_rx_p[53]]

# direction INPUT gt_rx_p[54]
set_property PACKAGE_PIN AL60 [get_ports gt_rx_p[54]]

# direction INPUT gt_rx_p[55]
set_property PACKAGE_PIN AL57 [get_ports gt_rx_p[55]]

# direction INPUT gt_rx_p[56]
set_property PACKAGE_PIN AJ60 [get_ports gt_rx_p[56]]

# direction INPUT gt_rx_p[57]
set_property PACKAGE_PIN AG60 [get_ports gt_rx_p[57]]

# direction INPUT gt_rx_p[58]
set_property PACKAGE_PIN AE60 [get_ports gt_rx_p[58]]

# direction INPUT gt_rx_p[59]
set_property PACKAGE_PIN AC57 [get_ports gt_rx_p[59]]

# direction INPUT gt_rx_p[60]
set_property PACKAGE_PIN AC60 [get_ports gt_rx_p[60]]

# direction INPUT gt_rx_p[61]
set_property PACKAGE_PIN AA60 [get_ports gt_rx_p[61]]

# direction INPUT gt_rx_p[62]
set_property PACKAGE_PIN AA57 [get_ports gt_rx_p[62]]

# direction INPUT gt_rx_p[63]
set_property PACKAGE_PIN W60 [get_ports gt_rx_p[63]]

# direction INPUT gt_rx_p[64]
set_property PACKAGE_PIN W57 [get_ports gt_rx_p[64]]

# direction INPUT gt_rx_p[65]
set_property PACKAGE_PIN U60 [get_ports gt_rx_p[65]]

# direction INPUT gt_rx_p[66]
set_property PACKAGE_PIN U57 [get_ports gt_rx_p[66]]

# direction INPUT gt_rx_p[67]
set_property PACKAGE_PIN R60 [get_ports gt_rx_p[67]]

# direction INPUT gt_rx_p[68]
set_property PACKAGE_PIN R57 [get_ports gt_rx_p[68]]

# direction INPUT gt_rx_n[1]
set_property PACKAGE_PIN C8 [get_ports gt_rx_n[1]]

# direction INPUT gt_rx_n[2]
set_property PACKAGE_PIN A9 [get_ports gt_rx_n[2]]

# direction INPUT gt_rx_n[3]
set_property PACKAGE_PIN E9 [get_ports gt_rx_n[3]]

# direction INPUT gt_rx_n[4]
set_property PACKAGE_PIN C10 [get_ports gt_rx_n[4]]

# direction INPUT gt_rx_n[5]
set_property PACKAGE_PIN A11 [get_ports gt_rx_n[5]]

# direction INPUT gt_rx_n[6]
set_property PACKAGE_PIN E11 [get_ports gt_rx_n[6]]

# direction INPUT gt_rx_n[7]
set_property PACKAGE_PIN C12 [get_ports gt_rx_n[7]]

# direction INPUT gt_rx_n[8]
set_property PACKAGE_PIN A13 [get_ports gt_rx_n[8]]

# direction INPUT gt_rx_n[9]
set_property PACKAGE_PIN E13 [get_ports gt_rx_n[9]]

# direction INPUT gt_rx_n[10]
set_property PACKAGE_PIN C14 [get_ports gt_rx_n[10]]

# direction INPUT gt_rx_n[11]
set_property PACKAGE_PIN A15 [get_ports gt_rx_n[11]]

# direction INPUT gt_rx_n[12]
set_property PACKAGE_PIN E15 [get_ports gt_rx_n[12]]

# direction INPUT gt_rx_n[13]
set_property PACKAGE_PIN C16 [get_ports gt_rx_n[13]]

# direction INPUT gt_rx_n[14]
set_property PACKAGE_PIN A17 [get_ports gt_rx_n[14]]

# direction INPUT gt_rx_n[15]
set_property PACKAGE_PIN E17 [get_ports gt_rx_n[15]]

# direction INPUT gt_rx_n[16]
set_property PACKAGE_PIN C18 [get_ports gt_rx_n[16]]

# direction INPUT gt_rx_n[17]
set_property PACKAGE_PIN A19 [get_ports gt_rx_n[17]]

# direction INPUT gt_rx_n[18]
set_property PACKAGE_PIN E19 [get_ports gt_rx_n[18]]

# direction INPUT gt_rx_n[19]
set_property PACKAGE_PIN C20 [get_ports gt_rx_n[19]]

# direction INPUT gt_rx_n[20]
set_property PACKAGE_PIN A21 [get_ports gt_rx_n[20]]

# direction INPUT gt_rx_n[21]
set_property PACKAGE_PIN BE59 [get_ports gt_rx_n[21]]

# direction INPUT gt_rx_n[22]
set_property PACKAGE_PIN BD61 [get_ports gt_rx_n[22]]

# direction INPUT gt_rx_n[23]
set_property PACKAGE_PIN BC59 [get_ports gt_rx_n[23]]

# direction INPUT gt_rx_n[24]
set_property PACKAGE_PIN BB61 [get_ports gt_rx_n[24]]

# direction INPUT gt_rx_n[25]
set_property PACKAGE_PIN BB57 [get_ports gt_rx_n[25]]

# direction INPUT gt_rx_n[26]
set_property PACKAGE_PIN BA59 [get_ports gt_rx_n[26]]

# direction INPUT gt_rx_n[27]
set_property PACKAGE_PIN AY61 [get_ports gt_rx_n[27]]

# direction INPUT gt_rx_n[28]
set_property PACKAGE_PIN AW59 [get_ports gt_rx_n[28]]

# direction INPUT gt_rx_n[29]
set_property PACKAGE_PIN E61 [get_ports gt_rx_n[29]]

# direction INPUT gt_rx_n[30]
set_property PACKAGE_PIN E59 [get_ports gt_rx_n[30]]

# direction INPUT gt_rx_n[31]
set_property PACKAGE_PIN C58 [get_ports gt_rx_n[31]]

# direction INPUT gt_rx_n[32]
set_property PACKAGE_PIN A57 [get_ports gt_rx_n[32]]

# direction INPUT gt_rx_n[33]
set_property PACKAGE_PIN E57 [get_ports gt_rx_n[33]]

# direction INPUT gt_rx_n[34]
set_property PACKAGE_PIN C56 [get_ports gt_rx_n[34]]

# direction INPUT gt_rx_n[35]
set_property PACKAGE_PIN A55 [get_ports gt_rx_n[35]]

# direction INPUT gt_rx_n[36]
set_property PACKAGE_PIN E55 [get_ports gt_rx_n[36]]

# direction INPUT gt_rx_n[37]
set_property PACKAGE_PIN C54 [get_ports gt_rx_n[37]]

# direction INPUT gt_rx_n[38]
set_property PACKAGE_PIN A53 [get_ports gt_rx_n[38]]

# direction INPUT gt_rx_n[39]
set_property PACKAGE_PIN E53 [get_ports gt_rx_n[39]]

# direction INPUT gt_rx_n[40]
set_property PACKAGE_PIN C52 [get_ports gt_rx_n[40]]

# direction INPUT gt_rx_n[41]
set_property PACKAGE_PIN A51 [get_ports gt_rx_n[41]]

# direction INPUT gt_rx_n[42]
set_property PACKAGE_PIN E51 [get_ports gt_rx_n[42]]

# direction INPUT gt_rx_n[43]
set_property PACKAGE_PIN C50 [get_ports gt_rx_n[43]]

# direction INPUT gt_rx_n[44]
set_property PACKAGE_PIN A49 [get_ports gt_rx_n[44]]

# direction INPUT gt_rx_n[45]
set_property PACKAGE_PIN E49 [get_ports gt_rx_n[45]]

# direction INPUT gt_rx_n[46]
set_property PACKAGE_PIN C48 [get_ports gt_rx_n[46]]

# direction INPUT gt_rx_n[47]
set_property PACKAGE_PIN A47 [get_ports gt_rx_n[47]]

# direction INPUT gt_rx_n[48]
set_property PACKAGE_PIN E47 [get_ports gt_rx_n[48]]

# direction INPUT gt_rx_n[49]
set_property PACKAGE_PIN C46 [get_ports gt_rx_n[49]]

# direction INPUT gt_rx_n[50]
set_property PACKAGE_PIN A45 [get_ports gt_rx_n[50]]

# direction INPUT gt_rx_n[51]
set_property PACKAGE_PIN E45 [get_ports gt_rx_n[51]]

# direction INPUT gt_rx_n[52]
set_property PACKAGE_PIN C44 [get_ports gt_rx_n[52]]

# direction INPUT gt_rx_n[53]
set_property PACKAGE_PIN AN58 [get_ports gt_rx_n[53]]

# direction INPUT gt_rx_n[54]
set_property PACKAGE_PIN AL61 [get_ports gt_rx_n[54]]

# direction INPUT gt_rx_n[55]
set_property PACKAGE_PIN AL58 [get_ports gt_rx_n[55]]

# direction INPUT gt_rx_n[56]
set_property PACKAGE_PIN AJ61 [get_ports gt_rx_n[56]]

# direction INPUT gt_rx_n[57]
set_property PACKAGE_PIN AG61 [get_ports gt_rx_n[57]]

# direction INPUT gt_rx_n[58]
set_property PACKAGE_PIN AE61 [get_ports gt_rx_n[58]]

# direction INPUT gt_rx_n[59]
set_property PACKAGE_PIN AC58 [get_ports gt_rx_n[59]]

# direction INPUT gt_rx_n[60]
set_property PACKAGE_PIN AC61 [get_ports gt_rx_n[60]]

# direction INPUT gt_rx_n[61]
set_property PACKAGE_PIN AA61 [get_ports gt_rx_n[61]]

# direction INPUT gt_rx_n[62]
set_property PACKAGE_PIN AA58 [get_ports gt_rx_n[62]]

# direction INPUT gt_rx_n[63]
set_property PACKAGE_PIN W61 [get_ports gt_rx_n[63]]

# direction INPUT gt_rx_n[64]
set_property PACKAGE_PIN W58 [get_ports gt_rx_n[64]]

# direction INPUT gt_rx_n[65]
set_property PACKAGE_PIN U61 [get_ports gt_rx_n[65]]

# direction INPUT gt_rx_n[66]
set_property PACKAGE_PIN U58 [get_ports gt_rx_n[66]]

# direction INPUT gt_rx_n[67]
set_property PACKAGE_PIN R61 [get_ports gt_rx_n[67]]

# direction INPUT gt_rx_n[68]
set_property PACKAGE_PIN R58 [get_ports gt_rx_n[68]]

# direction OUTPUT gt_tx_p[1]
set_property PACKAGE_PIN J8 [get_ports gt_tx_p[1]]

# direction OUTPUT gt_tx_p[2]
set_property PACKAGE_PIN N8 [get_ports gt_tx_p[2]]

# direction OUTPUT gt_tx_p[3]
set_property PACKAGE_PIN L9 [get_ports gt_tx_p[3]]

# direction OUTPUT gt_tx_p[4]
set_property PACKAGE_PIN J10 [get_ports gt_tx_p[4]]

# direction OUTPUT gt_tx_p[5]
set_property PACKAGE_PIN N10 [get_ports gt_tx_p[5]]

# direction OUTPUT gt_tx_p[6]
set_property PACKAGE_PIN L11 [get_ports gt_tx_p[6]]

# direction OUTPUT gt_tx_p[7]
set_property PACKAGE_PIN J12 [get_ports gt_tx_p[7]]

# direction OUTPUT gt_tx_p[8]
set_property PACKAGE_PIN N12 [get_ports gt_tx_p[8]]

# direction OUTPUT gt_tx_p[9]
set_property PACKAGE_PIN L13 [get_ports gt_tx_p[9]]

# direction OUTPUT gt_tx_p[10]
set_property PACKAGE_PIN J14 [get_ports gt_tx_p[10]]

# direction OUTPUT gt_tx_p[11]
set_property PACKAGE_PIN N14 [get_ports gt_tx_p[11]]

# direction OUTPUT gt_tx_p[12]
set_property PACKAGE_PIN L15 [get_ports gt_tx_p[12]]

# direction OUTPUT gt_tx_p[13]
set_property PACKAGE_PIN J16 [get_ports gt_tx_p[13]]

# direction OUTPUT gt_tx_p[14]
set_property PACKAGE_PIN N16 [get_ports gt_tx_p[14]]

# direction OUTPUT gt_tx_p[15]
set_property PACKAGE_PIN L17 [get_ports gt_tx_p[15]]

# direction OUTPUT gt_tx_p[16]
set_property PACKAGE_PIN J18 [get_ports gt_tx_p[16]]

# direction OUTPUT gt_tx_p[17]
set_property PACKAGE_PIN N18 [get_ports gt_tx_p[17]]

# direction OUTPUT gt_tx_p[18]
set_property PACKAGE_PIN L19 [get_ports gt_tx_p[18]]

# direction OUTPUT gt_tx_p[19]
set_property PACKAGE_PIN J20 [get_ports gt_tx_p[19]]

# direction OUTPUT gt_tx_p[20]
set_property PACKAGE_PIN N20 [get_ports gt_tx_p[20]]

# direction OUTPUT gt_tx_p[21]
set_property PACKAGE_PIN BE53 [get_ports gt_tx_p[21]]

# direction OUTPUT gt_tx_p[22]
set_property PACKAGE_PIN BD55 [get_ports gt_tx_p[22]]

# direction OUTPUT gt_tx_p[23]
set_property PACKAGE_PIN BD51 [get_ports gt_tx_p[23]]

# direction OUTPUT gt_tx_p[24]
set_property PACKAGE_PIN BC53 [get_ports gt_tx_p[24]]

# direction OUTPUT gt_tx_p[25]
set_property PACKAGE_PIN BB51 [get_ports gt_tx_p[25]]

# direction OUTPUT gt_tx_p[26]
set_property PACKAGE_PIN BA53 [get_ports gt_tx_p[26]]

# direction OUTPUT gt_tx_p[27]
set_property PACKAGE_PIN AY55 [get_ports gt_tx_p[27]]

# direction OUTPUT gt_tx_p[28]
set_property PACKAGE_PIN AY51 [get_ports gt_tx_p[28]]

# direction OUTPUT gt_tx_p[29]
set_property PACKAGE_PIN L61 [get_ports gt_tx_p[29]]

# direction OUTPUT gt_tx_p[30]
set_property PACKAGE_PIN J60 [get_ports gt_tx_p[30]]

# direction OUTPUT gt_tx_p[31]
set_property PACKAGE_PIN L59 [get_ports gt_tx_p[31]]

# direction OUTPUT gt_tx_p[32]
set_property PACKAGE_PIN J58 [get_ports gt_tx_p[32]]

# direction OUTPUT gt_tx_p[33]
set_property PACKAGE_PIN L57 [get_ports gt_tx_p[33]]

# direction OUTPUT gt_tx_p[34]
set_property PACKAGE_PIN J56 [get_ports gt_tx_p[34]]

# direction OUTPUT gt_tx_p[35]
set_property PACKAGE_PIN L55 [get_ports gt_tx_p[35]]

# direction OUTPUT gt_tx_p[36]
set_property PACKAGE_PIN J54 [get_ports gt_tx_p[36]]

# direction OUTPUT gt_tx_p[37]
set_property PACKAGE_PIN L53 [get_ports gt_tx_p[37]]

# direction OUTPUT gt_tx_p[38]
set_property PACKAGE_PIN J52 [get_ports gt_tx_p[38]]

# direction OUTPUT gt_tx_p[39]
set_property PACKAGE_PIN N52 [get_ports gt_tx_p[39]]

# direction OUTPUT gt_tx_p[40]
set_property PACKAGE_PIN L51 [get_ports gt_tx_p[40]]

# direction OUTPUT gt_tx_p[41]
set_property PACKAGE_PIN J50 [get_ports gt_tx_p[41]]

# direction OUTPUT gt_tx_p[42]
set_property PACKAGE_PIN N50 [get_ports gt_tx_p[42]]

# direction OUTPUT gt_tx_p[43]
set_property PACKAGE_PIN L49 [get_ports gt_tx_p[43]]

# direction OUTPUT gt_tx_p[44]
set_property PACKAGE_PIN J48 [get_ports gt_tx_p[44]]

# direction OUTPUT gt_tx_p[45]
set_property PACKAGE_PIN N48 [get_ports gt_tx_p[45]]

# direction OUTPUT gt_tx_p[46]
set_property PACKAGE_PIN L47 [get_ports gt_tx_p[46]]

# direction OUTPUT gt_tx_p[47]
set_property PACKAGE_PIN J46 [get_ports gt_tx_p[47]]

# direction OUTPUT gt_tx_p[48]
set_property PACKAGE_PIN N46 [get_ports gt_tx_p[48]]

# direction OUTPUT gt_tx_p[49]
set_property PACKAGE_PIN L45 [get_ports gt_tx_p[49]]

# direction OUTPUT gt_tx_p[50]
set_property PACKAGE_PIN J44 [get_ports gt_tx_p[50]]

# direction OUTPUT gt_tx_p[51]
set_property PACKAGE_PIN N44 [get_ports gt_tx_p[51]]

# direction OUTPUT gt_tx_p[52]
set_property PACKAGE_PIN L43 [get_ports gt_tx_p[52]]

# direction OUTPUT gt_tx_p[53]
set_property PACKAGE_PIN AM54 [get_ports gt_tx_p[53]]

# direction OUTPUT gt_tx_p[54]
set_property PACKAGE_PIN AK54 [get_ports gt_tx_p[54]]

# direction OUTPUT gt_tx_p[55]
set_property PACKAGE_PIN AJ57 [get_ports gt_tx_p[55]]

# direction OUTPUT gt_tx_p[56]
set_property PACKAGE_PIN AH54 [get_ports gt_tx_p[56]]

# direction OUTPUT gt_tx_p[57]
set_property PACKAGE_PIN AG57 [get_ports gt_tx_p[57]]

# direction OUTPUT gt_tx_p[58]
set_property PACKAGE_PIN AF54 [get_ports gt_tx_p[58]]

# direction OUTPUT gt_tx_p[59]
set_property PACKAGE_PIN AE57 [get_ports gt_tx_p[59]]

# direction OUTPUT gt_tx_p[60]
set_property PACKAGE_PIN AD54 [get_ports gt_tx_p[60]]

# direction OUTPUT gt_tx_p[61]
set_property PACKAGE_PIN AB54 [get_ports gt_tx_p[61]]

# direction OUTPUT gt_tx_p[62]
set_property PACKAGE_PIN Y54 [get_ports gt_tx_p[62]]

# direction OUTPUT gt_tx_p[63]
set_property PACKAGE_PIN Y51 [get_ports gt_tx_p[63]]

# direction OUTPUT gt_tx_p[64]
set_property PACKAGE_PIN V54 [get_ports gt_tx_p[64]]

# direction OUTPUT gt_tx_p[65]
set_property PACKAGE_PIN V51 [get_ports gt_tx_p[65]]

# direction OUTPUT gt_tx_p[66]
set_property PACKAGE_PIN T54 [get_ports gt_tx_p[66]]

# direction OUTPUT gt_tx_p[67]
set_property PACKAGE_PIN T51 [get_ports gt_tx_p[67]]

# direction OUTPUT gt_tx_p[68]
set_property PACKAGE_PIN P54 [get_ports gt_tx_p[68]]

# direction OUTPUT gt_tx_n[1]
set_property PACKAGE_PIN H8 [get_ports gt_tx_n[1]]

# direction OUTPUT gt_tx_n[2]
set_property PACKAGE_PIN M8 [get_ports gt_tx_n[2]]

# direction OUTPUT gt_tx_n[3]
set_property PACKAGE_PIN K9 [get_ports gt_tx_n[3]]

# direction OUTPUT gt_tx_n[4]
set_property PACKAGE_PIN H10 [get_ports gt_tx_n[4]]

# direction OUTPUT gt_tx_n[5]
set_property PACKAGE_PIN M10 [get_ports gt_tx_n[5]]

# direction OUTPUT gt_tx_n[6]
set_property PACKAGE_PIN K11 [get_ports gt_tx_n[6]]

# direction OUTPUT gt_tx_n[7]
set_property PACKAGE_PIN H12 [get_ports gt_tx_n[7]]

# direction OUTPUT gt_tx_n[8]
set_property PACKAGE_PIN M12 [get_ports gt_tx_n[8]]

# direction OUTPUT gt_tx_n[9]
set_property PACKAGE_PIN K13 [get_ports gt_tx_n[9]]

# direction OUTPUT gt_tx_n[10]
set_property PACKAGE_PIN H14 [get_ports gt_tx_n[10]]

# direction OUTPUT gt_tx_n[11]
set_property PACKAGE_PIN M14 [get_ports gt_tx_n[11]]

# direction OUTPUT gt_tx_n[12]
set_property PACKAGE_PIN K15 [get_ports gt_tx_n[12]]

# direction OUTPUT gt_tx_n[13]
set_property PACKAGE_PIN H16 [get_ports gt_tx_n[13]]

# direction OUTPUT gt_tx_n[14]
set_property PACKAGE_PIN M16 [get_ports gt_tx_n[14]]

# direction OUTPUT gt_tx_n[15]
set_property PACKAGE_PIN K17 [get_ports gt_tx_n[15]]

# direction OUTPUT gt_tx_n[16]
set_property PACKAGE_PIN H18 [get_ports gt_tx_n[16]]

# direction OUTPUT gt_tx_n[17]
set_property PACKAGE_PIN M18 [get_ports gt_tx_n[17]]

# direction OUTPUT gt_tx_n[18]
set_property PACKAGE_PIN K19 [get_ports gt_tx_n[18]]

# direction OUTPUT gt_tx_n[19]
set_property PACKAGE_PIN H20 [get_ports gt_tx_n[19]]

# direction OUTPUT gt_tx_n[20]
set_property PACKAGE_PIN M20 [get_ports gt_tx_n[20]]

# direction OUTPUT gt_tx_n[21]
set_property PACKAGE_PIN BE54 [get_ports gt_tx_n[21]]

# direction OUTPUT gt_tx_n[22]
set_property PACKAGE_PIN BD56 [get_ports gt_tx_n[22]]

# direction OUTPUT gt_tx_n[23]
set_property PACKAGE_PIN BD52 [get_ports gt_tx_n[23]]

# direction OUTPUT gt_tx_n[24]
set_property PACKAGE_PIN BC54 [get_ports gt_tx_n[24]]

# direction OUTPUT gt_tx_n[25]
set_property PACKAGE_PIN BB52 [get_ports gt_tx_n[25]]

# direction OUTPUT gt_tx_n[26]
set_property PACKAGE_PIN BA54 [get_ports gt_tx_n[26]]

# direction OUTPUT gt_tx_n[27]
set_property PACKAGE_PIN AY56 [get_ports gt_tx_n[27]]

# direction OUTPUT gt_tx_n[28]
set_property PACKAGE_PIN AY52 [get_ports gt_tx_n[28]]

# direction OUTPUT gt_tx_n[29]
set_property PACKAGE_PIN K61 [get_ports gt_tx_n[29]]

# direction OUTPUT gt_tx_n[30]
set_property PACKAGE_PIN H60 [get_ports gt_tx_n[30]]

# direction OUTPUT gt_tx_n[31]
set_property PACKAGE_PIN K59 [get_ports gt_tx_n[31]]

# direction OUTPUT gt_tx_n[32]
set_property PACKAGE_PIN H58 [get_ports gt_tx_n[32]]

# direction OUTPUT gt_tx_n[33]
set_property PACKAGE_PIN K57 [get_ports gt_tx_n[33]]

# direction OUTPUT gt_tx_n[34]
set_property PACKAGE_PIN H56 [get_ports gt_tx_n[34]]

# direction OUTPUT gt_tx_n[35]
set_property PACKAGE_PIN K55 [get_ports gt_tx_n[35]]

# direction OUTPUT gt_tx_n[36]
set_property PACKAGE_PIN H54 [get_ports gt_tx_n[36]]

# direction OUTPUT gt_tx_n[37]
set_property PACKAGE_PIN K53 [get_ports gt_tx_n[37]]

# direction OUTPUT gt_tx_n[38]
set_property PACKAGE_PIN H52 [get_ports gt_tx_n[38]]

# direction OUTPUT gt_tx_n[39]
set_property PACKAGE_PIN M52 [get_ports gt_tx_n[39]]

# direction OUTPUT gt_tx_n[40]
set_property PACKAGE_PIN K51 [get_ports gt_tx_n[40]]

# direction OUTPUT gt_tx_n[41]
set_property PACKAGE_PIN H50 [get_ports gt_tx_n[41]]

# direction OUTPUT gt_tx_n[42]
set_property PACKAGE_PIN M50 [get_ports gt_tx_n[42]]

# direction OUTPUT gt_tx_n[43]
set_property PACKAGE_PIN K49 [get_ports gt_tx_n[43]]

# direction OUTPUT gt_tx_n[44]
set_property PACKAGE_PIN H48 [get_ports gt_tx_n[44]]

# direction OUTPUT gt_tx_n[45]
set_property PACKAGE_PIN M48 [get_ports gt_tx_n[45]]

# direction OUTPUT gt_tx_n[46]
set_property PACKAGE_PIN K47 [get_ports gt_tx_n[46]]

# direction OUTPUT gt_tx_n[47]
set_property PACKAGE_PIN H46 [get_ports gt_tx_n[47]]

# direction OUTPUT gt_tx_n[48]
set_property PACKAGE_PIN M46 [get_ports gt_tx_n[48]]

# direction OUTPUT gt_tx_n[49]
set_property PACKAGE_PIN K45 [get_ports gt_tx_n[49]]

# direction OUTPUT gt_tx_n[50]
set_property PACKAGE_PIN H44 [get_ports gt_tx_n[50]]

# direction OUTPUT gt_tx_n[51]
set_property PACKAGE_PIN M44 [get_ports gt_tx_n[51]]

# direction OUTPUT gt_tx_n[52]
set_property PACKAGE_PIN K43 [get_ports gt_tx_n[52]]

# direction OUTPUT gt_tx_n[53]
set_property PACKAGE_PIN AM55 [get_ports gt_tx_n[53]]

# direction OUTPUT gt_tx_n[54]
set_property PACKAGE_PIN AK55 [get_ports gt_tx_n[54]]

# direction OUTPUT gt_tx_n[55]
set_property PACKAGE_PIN AJ58 [get_ports gt_tx_n[55]]

# direction OUTPUT gt_tx_n[56]
set_property PACKAGE_PIN AH55 [get_ports gt_tx_n[56]]

# direction OUTPUT gt_tx_n[57]
set_property PACKAGE_PIN AG58 [get_ports gt_tx_n[57]]

# direction OUTPUT gt_tx_n[58]
set_property PACKAGE_PIN AF55 [get_ports gt_tx_n[58]]

# direction OUTPUT gt_tx_n[59]
set_property PACKAGE_PIN AE58 [get_ports gt_tx_n[59]]

# direction OUTPUT gt_tx_n[60]
set_property PACKAGE_PIN AD55 [get_ports gt_tx_n[60]]

# direction OUTPUT gt_tx_n[61]
set_property PACKAGE_PIN AB55 [get_ports gt_tx_n[61]]

# direction OUTPUT gt_tx_n[62]
set_property PACKAGE_PIN Y55 [get_ports gt_tx_n[62]]

# direction OUTPUT gt_tx_n[63]
set_property PACKAGE_PIN Y52 [get_ports gt_tx_n[63]]

# direction OUTPUT gt_tx_n[64]
set_property PACKAGE_PIN V55 [get_ports gt_tx_n[64]]

# direction OUTPUT gt_tx_n[65]
set_property PACKAGE_PIN V52 [get_ports gt_tx_n[65]]

# direction OUTPUT gt_tx_n[66]
set_property PACKAGE_PIN T55 [get_ports gt_tx_n[66]]

# direction OUTPUT gt_tx_n[67]
set_property PACKAGE_PIN T52 [get_ports gt_tx_n[67]]

# direction OUTPUT gt_tx_n[68]
set_property PACKAGE_PIN P55 [get_ports gt_tx_n[68]]

# direction INOUT system_scl
create_clock -period 2500.0 -name system_scl [get_ports system_scl]
set_property IOSTANDARD LVCMOS12 [get_ports system_scl]
set_property PACKAGE_PIN CA28 [get_ports system_scl]

# direction INOUT system_sda
set_property IOSTANDARD LVCMOS12 [get_ports system_sda]
set_property PACKAGE_PIN CA29 [get_ports system_sda]

# direction INOUT application_scl
create_clock -period 2500.0 -name application_scl [get_ports application_scl]
set_property IOSTANDARD LVCMOS12 [get_ports application_scl]
set_property PACKAGE_PIN CA27 [get_ports application_scl]

# direction INOUT application_sda
set_property IOSTANDARD LVCMOS12 [get_ports application_sda]
set_property PACKAGE_PIN BY28 [get_ports application_sda]

# direction INOUT eeprom_scl
create_clock -period 2500.0 -name eeprom_scl [get_ports eeprom_scl]
set_property IOSTANDARD LVCMOS12 [get_ports eeprom_scl]
set_property PACKAGE_PIN CA34 [get_ports eeprom_scl]

# direction INOUT eeprom_sda
set_property IOSTANDARD LVCMOS12 [get_ports eeprom_sda]
set_property PACKAGE_PIN CA33 [get_ports eeprom_sda]

# direction OUTPUT seu_error
set_property IOSTANDARD LVCMOS12 [get_ports seu_error]
set_property PACKAGE_PIN BR32 [get_ports seu_error]

# direction OUTPUT sysmon_alert
set_property IOSTANDARD LVCMOS12 [get_ports sysmon_alert]
set_property PACKAGE_PIN BP32 [get_ports sysmon_alert]

# direction INPUT fpga_id[0]
set_property IOSTANDARD LVCMOS12 [get_ports fpga_id[0]]
set_property PULLUP TRUE [get_ports fpga_id[0]]
set_property PACKAGE_PIN BK25 [get_ports fpga_id[0]]

# direction INPUT fpga_id[1]
set_property IOSTANDARD LVCMOS12 [get_ports fpga_id[1]]
set_property PULLUP TRUE [get_ports fpga_id[1]]
set_property PACKAGE_PIN BJ27 [get_ports fpga_id[1]]

# direction INPUT fpga_id[2]
set_property IOSTANDARD LVCMOS12 [get_ports fpga_id[2]]
set_property PULLUP TRUE [get_ports fpga_id[2]]
set_property PACKAGE_PIN BJ26 [get_ports fpga_id[2]]

# direction INOUT gpio[0]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[0]]
set_property PULLUP TRUE [get_ports gpio[0]]
set_property PACKAGE_PIN BN35 [get_ports gpio[0]]

# direction INOUT gpio[1]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[1]]
set_property PULLUP TRUE [get_ports gpio[1]]
set_property PACKAGE_PIN BM34 [get_ports gpio[1]]

# direction INOUT gpio[2]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[2]]
set_property PULLUP TRUE [get_ports gpio[2]]
set_property PACKAGE_PIN BM33 [get_ports gpio[2]]

# direction INOUT gpio[3]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[3]]
set_property PULLUP TRUE [get_ports gpio[3]]
set_property PACKAGE_PIN BM32 [get_ports gpio[3]]

# direction INOUT gpio[4]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[4]]
set_property PULLUP TRUE [get_ports gpio[4]]
set_property PACKAGE_PIN BL34 [get_ports gpio[4]]

# direction INOUT gpio[5]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[5]]
set_property PULLUP TRUE [get_ports gpio[5]]
set_property PACKAGE_PIN BL33 [get_ports gpio[5]]

# direction INOUT gpio[6]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[6]]
set_property PULLUP TRUE [get_ports gpio[6]]
set_property PACKAGE_PIN BK35 [get_ports gpio[6]]

# direction INOUT gpio[7]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[7]]
set_property PULLUP TRUE [get_ports gpio[7]]
set_property PACKAGE_PIN BK34 [get_ports gpio[7]]

# direction INOUT gpio[8]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[8]]
set_property PULLUP TRUE [get_ports gpio[8]]
set_property PACKAGE_PIN BK32 [get_ports gpio[8]]

# direction INOUT gpio[9]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[9]]
set_property PULLUP TRUE [get_ports gpio[9]]
set_property PACKAGE_PIN BJ32 [get_ports gpio[9]]

# direction INOUT gpio[10]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[10]]
set_property PULLUP TRUE [get_ports gpio[10]]
set_property PACKAGE_PIN BJ35 [get_ports gpio[10]]

# direction INOUT gpio[11]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[11]]
set_property PULLUP TRUE [get_ports gpio[11]]
set_property PACKAGE_PIN BH34 [get_ports gpio[11]]

# direction INOUT gpio[12]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[12]]
set_property PULLUP TRUE [get_ports gpio[12]]
set_property PACKAGE_PIN BG35 [get_ports gpio[12]]

# direction INOUT gpio[13]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[13]]
set_property PULLUP TRUE [get_ports gpio[13]]
set_property PACKAGE_PIN BG34 [get_ports gpio[13]]

# direction INOUT gpio[14]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[14]]
set_property PULLUP TRUE [get_ports gpio[14]]
set_property PACKAGE_PIN BH33 [get_ports gpio[14]]

# direction INOUT gpio[15]
set_property IOSTANDARD LVCMOS12 [get_ports gpio[15]]
set_property PULLUP TRUE [get_ports gpio[15]]
set_property PACKAGE_PIN BK31 [get_ports gpio[15]]

